### DISCUSSION TITLE
Unable to pull updates

### DISCUSSION THREAD

**Discussion by elixdreamer** [netbox-community/netbox-docker#1030] [Getting Help]
### Current Behavior

When performing an update/pull i get the warning that access is denied for netbox.
Currently i'm running netbox 3.5.3

```
user@debian-docker:~/projects/netbox-docker$ sudo docker compose pull
[sudo] password for user: 
[+] Running 11/12
 ⠿ netbox-housekeeping Skipped - Image is already being pulled by netbox                                                                                                                                       0.0s
 ⠿ netbox-worker Skipped - Image is already being pulled by netbox                                                                                                                                             0.0s
 ⠿ redis-cache Skipped - Image is already being pulled by redis                                                                                                                                                0.0s
 ⠿ redis-worker-exporter Skipped - Image is already being pulled by redis-cache-exporter                                                                                                                       0.0s
 ⠿ grafana Pulled                                                                                                                                                                                              0.9s
 ⠿ postgres-exporter Pulled                                                                                                                                                                                    0.9s
 ⠿ netbox Warning                                                                                                                                                                                              1.1s
 ⠿ prometheus Pulled                                                                                                                                                                                           0.9s
 ⠿ postgres Pulled                                                                                                                                                                                             0.9s
 ⠿ redis Pulled                                                                                                                                                                                                0.9s
 ⠿ tls Pulled                                                                                                                                                                                                  0.9s
 ⠿ redis-cache-exporter Pulled                                                                                                                                                                                 0.9s
WARNING: Some service image(s) must be built from source by running:
    docker compose build netbox
1 error occurred:
        * Error response from daemon: pull access denied for netbox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

### Expected Behavior

PULL request working fine and updating Netbox to latest version 3.5.5

### Docker Compose Version

Docker Compose version v2.16.0

### Docker Version

```text
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

22486fefb5c4cc326bd091abeac5314eb7acd37f

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
no related logs can be shared
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  # netbox
  netbox:
    environment:
      METRICS_ENABLED: 'true'
    volumes:
    - type: tmpfs
      target: /tmp/metrics
      read_only: false
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
  
  # netbox-worker
  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  # netbox-housekeeping
  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  # postgres
  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    depends_on:
    - postgres
    environment:
      DATA_SOURCE_URI: postgres?sslmode=disable
      DATA_SOURCE_USER: netbox
      DATA_SOURCE_PASS: <password>
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: 'true'

  # redis
  redis-worker-exporter:
    image: oliver006/redis_exporter
    depends_on:
    - redis
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_PASSWORD: <password>
  redis-cache-exporter:
    image: oliver006/redis_exporter
    depends_on:
    - redis-cache
    environment:
      REDIS_ADDR: redis://redis-cache:6379
      REDIS_PASSWORD: <password>

  # prometheus
  prometheus:
    image: prom/prometheus:v2.22.0
    depends_on:
    - postgres-exporter
    - redis-cache-exporter
    - redis-worker-exporter
    - netbox
    ports:
    - '9090:9090'
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus/data

  # grafana
  grafana:
    image: grafana/grafana:7.2.1
    depends_on:
    - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_SECRET_KEY: <secret>
      GF_METRICS_ENABLED: 'true'
    ports:
    - '3000:3000'
    volumes:
    #- ./monitoring/grafana/plugins/:/var/lib/grafana/plugins/:z,ro
    #- ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/:z,ro
    #- ./monitoring/grafana/dashboards/:/etc/grafana/dashboards/:z,ro
    - grafana-data:/var/lib/grafana

  # TLS HTTPS
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - ./Caddy/10.127.103.157.pem:/etc/ssl/private/cert.crt:ro,z
      - ./Caddy/10.127.103.157-key.pem:/etc/ssl/private/key.key:ro,z
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80   # Allows for http redirection
      - 443:443

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
```
