### DISCUSSION TITLE
Issues with static files on 2.6.1

### DISCUSSION THREAD

**Discussion by twiclo** [netbox-community/netbox-docker#1038] [Getting Help] [answered]
I'm running netbox 2.6.1 to get some legacy software working so we can migrate off of it. I'm running into an issue where all of the static files are 404ing. In the container I can see that they're there and I've ran `manage.py collectstatic` which modified nothing. It doesn't look like this is dependent on any config file but nonetheless here's the section from my compose.yaml
```
  netbox:
    image: netboxcommunity/netbox:v2.6.1
    environment:
      ALLOWED_HOSTS: localhost
      SECRET_KEY: Scs5ZtqaMRVewg38
      SUPERUSER_EMAIL: ${GENERAL_EMAIL}
      SUPERUSER_PASSWORD: ${GENERAL_PASSWORD}
      DB_HOST: pg
      DB_USER: postgres
      DB_PASSWORD: ${GENERAL_PASSWORD}
      REDIS_HOST: cache
    ports:
      - "8002:8001"
    depends_on:
      - pg
      - cache
```

It looks like there used to be a `BASE_PATH` variable but I don't think it applies here
