### DISCUSSION TITLE
Trying to get this working in azure app service is painful

### DISCUSSION THREAD

**Discussion by craftzneko** [netbox-community/netbox-docker#1054] [Getting Help]
Trying to get this hosted in azure app service as a docker compose option have hit numerous issues. As AAS doesnt like anchors in docker compose i had to run them seperatly, does this cause problems. I seem to be getting this issue, i have no idea how to solve in the worker and housekeeping containers

2023-08-17T12:09:07.599421569Z   File "/etc/netbox/config/configuration.py", line 45, in <lambda>
2023-08-17T12:09:07.599425270Z     _AS_INT = lambda value : int(value)
2023-08-17T12:09:07.599428870Z ValueError: invalid literal for int() with base 10: ''

My docker compose looks like this

```
version: '3.4'

services:
  netbox:
    image: netboxcommunity/netbox:latest
    depends_on:
    - redis
    - redis-cache
    user: 'unit:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/api/ || exit 1"
    volumes:
    - ${WEBAPP_STORAGE_HOME}/./configuration:/etc/netbox/config
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/opt/netbox/netbox/reports
    - netbox-scripts-files:/opt/netbox/netbox/scripts

  netbox-worker:
    image: netboxcommunity/netbox:latest
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"

  netbox-housekeeping:
    image: netboxcommunity/netbox:latest
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q housekeeping || exit 1"
```

Left out the redis as they come up fine
