### DISCUSSION TITLE
Unable to connect my AD with the LDAP of netbox?

### DISCUSSION THREAD

**Discussion by JTzLinux** [netbox-community/netbox-docker#1064] [Getting Help] [answered]
Hello everyone I am trying to connect the AD to my netbox but it doesnt seem to work no matter what I do :/ I would love to get help

**docker-compose.override.yml:**
```
version: '3.4'
services:
  netbox:
    ports:
      - "8000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: ""
      SUPERUSER_EMAIL: "**HIDDEN**"
      SUPERUSER_NAME: "**HIDDEN**"
      SUPERUSER_PASSWORD: "**HIDDEN**"
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldap://**HIDDEN**"
      AUTH_LDAP_BIND_DN: "CN=LSAD,OU=Computern,OU=IT,DC=SIMONZ,DC=local"
      AUTH_LDAP_BIND_PASSWORD: "**HIDDEN**"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=Benutzern,OU=IT,DC=SIMONZ,DC=local"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=Gruppen,OU=IT,DC=SIMONZ,DC=local"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-Users,OU=Gruppen,OU=IT,DC=SIMONZ,DC=local"
      AUTH_LDAP_GROUP_TYPE: "NestedGroupOfNamesType"
      AUTH_LDAP_IS_ADMIN_DN: "CN=NetBox-Admin,OU=Gruppen,OU=IT,DC=SIMONZ,DC=local"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=NetBox-Owner,OU=Gruppen,OU=IT,DC=SIMONZ,DC=local"
      LDAP_IGNORE_CERT_ERRORS: "true"

```
**Log:**
```
root@debian:/opt/containers/netbox# docker compose up
[+] Running 6/0
 ✔ Container netbox-redis-1                Created                                                                                                                                                                                      0.0s
 ✔ Container netbox-redis-cache-1          Created                                                                                                                                                                                      0.0s
 ✔ Container netbox-postgres-1             Created                                                                                                                                                                                      0.0s
 ✔ Container netbox-netbox-1               Created                                                                                                                                                                                      0.0s
 ✔ Container netbox-netbox-worker-1        Created                                                                                                                                                                                      0.0s
 ✔ Container netbox-netbox-housekeeping-1  Created                                                                                                                                                                                      0.0s
Attaching to netbox-netbox-1, netbox-netbox-housekeeping-1, netbox-netbox-worker-1, netbox-postgres-1, netbox-redis-1, netbox-redis-cache-1
netbox-redis-1                | 1:C 31 Aug 2023 12:10:35.759 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
netbox-redis-1                | 1:C 31 Aug 2023 12:10:35.759 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
netbox-redis-1                | 1:C 31 Aug 2023 12:10:35.759 * Redis version=7.2.0, bits=64, commit=00000000, modified=0, pid=1, just started
netbox-redis-1                | 1:C 31 Aug 2023 12:10:35.759 * Configuration loaded
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.759 * monotonic clock: POSIX clock_gettime
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.759 * Running mode=standalone, port=6379.
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * Server initialized
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * Reading RDB base file on AOF loading...
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * Loading RDB produced by version 7.2.0
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * RDB age 8931 seconds
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * RDB memory usage when created 0.83 Mb
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * RDB is base AOF
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * Done loading RDB, keys loaded: 0, keys expired: 0.
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.760 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.796 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.036 seconds
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.796 * DB loaded from append only file: 0.036 seconds
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.796 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
netbox-redis-1                | 1:M 31 Aug 2023 12:10:35.796 * Ready to accept connections tcp
netbox-redis-cache-1          | 1:C 31 Aug 2023 12:10:35.860 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
netbox-redis-cache-1          | 1:C 31 Aug 2023 12:10:35.860 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
netbox-redis-cache-1          | 1:C 31 Aug 2023 12:10:35.860 * Redis version=7.2.0, bits=64, commit=00000000, modified=0, pid=1, just started
netbox-redis-cache-1          | 1:C 31 Aug 2023 12:10:35.860 * Configuration loaded
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.860 * monotonic clock: POSIX clock_gettime
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.861 * Running mode=standalone, port=6379.
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.861 * Server initialized
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.861 * Loading RDB produced by version 7.2.0
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.861 * RDB age 4354 seconds
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.861 * RDB memory usage when created 0.95 Mb
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.862 * Done loading RDB, keys loaded: 2, keys expired: 0.
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.862 * DB loaded from disk: 0.001 seconds
netbox-redis-cache-1          | 1:M 31 Aug 2023 12:10:35.862 * Ready to accept connections tcp
netbox-postgres-1             |
netbox-postgres-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
netbox-postgres-1             |
netbox-postgres-1             |
netbox-postgres-1             | 2023-08-31 12:10:35.962 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
netbox-postgres-1             | 2023-08-31 12:10:35.963 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
netbox-postgres-1             | 2023-08-31 12:10:35.963 UTC [1] LOG:  listening on IPv6 address "::", port 5432
netbox-postgres-1             | 2023-08-31 12:10:35.965 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
netbox-postgres-1             | 2023-08-31 12:10:35.968 UTC [24] LOG:  database system was interrupted; last known up at 2023-08-31 12:08:48 UTC
netbox-postgres-1             | 2023-08-31 12:10:35.995 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
netbox-postgres-1             | 2023-08-31 12:10:35.997 UTC [24] LOG:  redo starts at 0/23FE448
netbox-postgres-1             | 2023-08-31 12:10:35.997 UTC [24] LOG:  invalid record length at 0/23FE480: wanted 24, got 0
netbox-postgres-1             | 2023-08-31 12:10:35.997 UTC [24] LOG:  redo done at 0/23FE448 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
netbox-postgres-1             | 2023-08-31 12:10:36.000 UTC [22] LOG:  checkpoint starting: end-of-recovery immediate wait
netbox-postgres-1             | 2023-08-31 12:10:36.005 UTC [22] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.002 s, total=0.006 s; sync files=2, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
netbox-postgres-1             | 2023-08-31 12:10:36.010 UTC [1] LOG:  database system is ready to accept connections
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-1               | 💡 Superuser Username: Admin, E-Mail: **HIDDEN**
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-1               | ✅ Initialisation is done.
netbox-netbox-1               | 2023/08/31 12:11:01 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 7#7 unit 1.29.1 started
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 22#22 discovery started
netbox-netbox-1               | 2023/08/31 12:11:01 [notice] 22#22 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 7#7 controller started
netbox-netbox-1               | 2023/08/31 12:11:01 [notice] 7#7 process 22 exited with code 0
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 24#24 router started
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 24#24 OpenSSL 3.0.2 15 Mar 2022, 30000020
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 25#25 "netbox" prototype started
netbox-netbox-1               | 2023/08/31 12:11:01 [info] 26#26 "netbox" application started
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-1               | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-netbox-1               | ✅ Unit configuration loaded successfully
netbox-netbox-1               | 2023/08/31 12:11:07 [notice] 7#7 process 20 exited with code 0
netbox-netbox-1               | 2023/08/31 12:11:07 [info] 38#38 "netbox" application started
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-1               |
netbox-netbox-1               |
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-1               |
netbox-netbox-1               |
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-1               |
netbox-netbox-1               |
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-1               |
netbox-netbox-1               |
netbox-netbox-1               | 127.0.0.1 - - [31/Aug/2023:12:11:09 +0000] "GET /api/ HTTP/1.1" 200 510 "-" "curl/7.81.0"
netbox-netbox-housekeeping-1  | Interval set to 86400 seconds
netbox-netbox-housekeeping-1  | Thu Aug 31 12:11:09 UTC 2023
netbox-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-housekeeping-1  |
netbox-netbox-housekeeping-1  |
netbox-netbox-1               | 192.168.1.102 - - [31/Aug/2023:12:11:09 +0000] "GET /login/ HTTP/1.1" 200 4860 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"
netbox-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-worker-1        | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-housekeeping-1  | [*] Clearing expired authentication sessions
netbox-netbox-housekeeping-1  |         Sessions cleared.
netbox-netbox-housekeeping-1  | [*] Checking for expired changelog records
netbox-netbox-housekeeping-1  |         No expired records found.
netbox-netbox-housekeeping-1  | [*] Checking for expired jobs
netbox-netbox-housekeeping-1  |         No expired records found.
netbox-netbox-housekeeping-1  | [*] Checking for latest release
netbox-netbox-worker-1        | No queues have been specified. This process will service the following queues by default: high, default, low
netbox-netbox-worker-1        | 12:11:16 Worker rq:worker:27629f465117427384323f43414b311d started with PID 7, version 1.15.1
netbox-netbox-worker-1        | 12:11:16 Subscribing to channel rq:pubsub:27629f465117427384323f43414b311d
netbox-netbox-worker-1        | 12:11:16 *** Listening on high, default, low...
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/ldap/ldap_config.py'
netbox-netbox-1               | 🧬 loaded config '/etc/netbox/config/ldap/extra.py'
netbox-netbox-1               | WARNING Caught LDAPError while authenticating tomics: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090434, comment: AcceptSecurityContext error, data 52e, v4f7c'})
netbox-netbox-1               | 192.168.1.102 - - [31/Aug/2023:12:11:19 +0000] "POST /login/ HTTP/1.1" 200 5739 "http://192.168.1.3:8000/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"
netbox-netbox-housekeeping-1  |         Latest release: 3.6.0
netbox-netbox-housekeeping-1  | Finished.
netbox-netbox-1               | 127.0.0.1 - - [31/Aug/2023:12:11:24 +0000] "GET /api/ HTTP/1.1" 200 510 "-" "curl/7.81.0"

```
That is all I hope? thanks for any help I will get and I thank you all in advance!

**Comment by JTzLinux** [comment, marked as answer]
Problem was in the "AUTH_LDAP_BIND_DN" in the documentation the OU was called "EmbeddedDevices" so I thought it was something about Computers due to me never using LDAP so I thought I had to write in where all the Computers are Saved so after I noticed the flaw I changed it to my users and then it started working

**Reply by sudo-kraken** [reply]
I am having a similar issue would you be so kind as to share you compose, I am not using overides I just put it all in the one file but I cant get it to work, it says the ldap_config.py isnt picking up the env vars, are you using the provided ldap_config.py

**Reply by JTzLinux** [reply]
@Joeharrison94 sure can do I will send it tomorrow (UTC) due to me currently being out of house for the full day

**Comment by sudo-kraken** [comment]
brilliant thank you, the only thing I cant get working is the ldap it seems impossible

------- Original Message -------

**Reply by JTzLinux** [reply]
```
version: '3.4'
services:
  netbox:
    restart: always
    ports:
      - "192.168.1.3:8000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: ""
      SUPERUSER_EMAIL: "**HIDDEN**"
      SUPERUSER_NAME: "Admin"
      SUPERUSER_PASSWORD: "Tester123"
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldap://SIMONZ.local"
      AUTH_LDAP_BIND_DN: "CN=None,OU=Benutzern,OU=IT,DC=SIMONZ,dc=local"
      AUTH_LDAP_BIND_PASSWORD: "**HIDDEN**"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=Benutzern,OU=IT,DC=SIMONZ,dc=local"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=Gruppen,OU=IT,DC=SIMONZ,dc=local"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-Users,OU=Gruppen,OU=IT,DC=SIMONZ,dc=local"
      AUTH_LDAP_GROUP_TYPE: "NestedGroupOfNamesType"
      AUTH_LDAP_IS_ADMIN_DN: "CN=NetBox-Admin,OU=Gruppen,OU=IT,DC=SIMONZ,dc=local"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=NetBox-Owner,OU=Gruppen,OU=IT,DC=SIMONZ,dc=local"
      LDAP_IGNORE_CERT_ERRORS: "true"
```
**Note:** Cause this is not an acutally online server just a test domain I can just put it up just edit the informations with the ones of your AD use the ADSI-Editor to find out the right things to use for your env (The user of the netbox login requires to be an AD Administrator for some reason) if you need some help contact me my email is on my profile ^^
