### DISCUSSION TITLE
TLS with Caddy not working. No certificate found on server

### DISCUSSION THREAD

**Discussion by kirillmuravyev** [netbox-community/netbox-docker#1092] [Getting Help] [answered]
Hello All!
I am facing an issue trying to enable TLS using netbox docker guide:
![image](https://github.com/netbox-community/netbox-docker/assets/40544508/7c08f7fe-5e01-4f65-9c09-a42240e1031e)

Here is my docker-compose and Caddyfile:

```
./Caddyfile

10.240.2.7 {   # This line should match the ALLOWED_HOSTS in your NetBox Docker configuration
    reverse_proxy netbox:8080
    encode gzip zstd

    tls /etc/ssl/private/cert.crt /etc/ssl/private/key.key

    log {
      level error
    }
}
```

```
./docker-compose.overrride.yml

version: '3.4'
services:
  netbox:
    image: netbox:latest-plugins
    ports:
    - 8000:8080
    environment:
      ALLOWED_HOSTS: "10.240.2.7"
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - ./server.crt:/etc/ssl/private/cert.crt:ro,z
      - ./server.key:/etc/ssl/private/key.key:ro,z
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 8080:80
      - 8443:443
```

Certificate was created using command:
```openssl req -newkey rsa:4096 -nodes -sha256 -keyout server.key -x509 -days 365 -out server.crt -subj '/CN=10.240.2.7/'```

I dont see any error messages in logs

Inside tls container I can see certificates imported:
```
 podman exec -it  netbox-docker_tls_1 ls -l /etc/ssl/private
total 8
-rw-r-----    1 root     root          1809 Sep 27 09:59 cert.crt
-rw-------    1 root     root          3272 Sep 27 09:59 key.key
```

What could be the problem?
