### DISCUSSION TITLE
Bad file format reading the append only file appendonly.aof.2.incr.aof

### DISCUSSION THREAD

**Discussion by ragman1976** [netbox-community/netbox-docker#1123] [Getting Help]
Hi,

when I start the docker container(s) with docker compose up I get the following error message in the redis container log fiole:

Bad file format reading the append only file appendonly.aof.2.incr.aof: make a backup of your AOF file, then use ./redis-check-aof --fix <filename.manifest>

I don`t know where I should start the command "redis-check-aof --fix <filename.manifest>" and which filte name I have to enter.

Any hints?

Regards

**Comment by imartinezmorales-loom** [comment]
Did you end up figuring this out? I'm stuck on this currently

**Reply by ragman1976** [reply]
No mate. I switched to a Proxmox LXC running netbox on it.

**Reply by philip-pannenko** [reply]
I ran into the same problem listed above on my local machine dev deployment. By removing the `--appendonly yes` from the redis command, I got past the error. I'm not saying this is the right way to go and maybe I didn't get tripped up by any future issues yet, but it got me past the issue for now and allowed me to continue to locally develop. YMMV.
 
```
redis:
    image: docker.io/redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    # - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - netbox-redis-data:/data
    ```
