### DISCUSSION TITLE
Issue change the CHANGELOG_RETENTION interval

### DISCUSSION THREAD

**Discussion by fatman00** [netbox-community/netbox-docker#1140] [Getting Help]
Hi,

I have tried to change the changelog retention on the netbox from the default 90 days to some years.
I have done this by setting "CHANGELOG_RETENTION=3650" in /netbox-docker/env/netbox.env but after a docker compose down/up the change is not in effect.
Am I doing something wrong? 
I found an issue [#14182](https://github.com/netbox-community/netbox/issues/14182) but it should be fixed in 3.6.5(the version I am running)

Any help in troubleshooting this issue is appresiated.

**Comment by CrawliestCotter** [comment]
I know it's been a while, but I believe I found the solution to this.
You should be changing the enviroment variables in the ./docker-compose.override.yml file instead of the ./env/netbox.env file.
Do this by adding the following code to your docker-compose.override.yml:

### ./docker-compose.override.yml
```
services:
  netbox:
    environment:
      - CHANGELOG_RETENTION=3650

  netbox-worker:
    environment:
      - CHANGELOG_RETENTION=3650

  netbox-housekeeping:
    environment:
      - CHANGELOG_RETENTION=3650

```

You can also change the value to 0, to make the changelog retention indefinite. 
(It will show as "Changelog retention 0" in admin > system, but as "Change log retention: Indefinite" at the bottom of the change log page (operations > changelog))
