### DISCUSSION TITLE
Server Error 'NoneType' object has no attribute 'get_absolute_url'

### DISCUSSION THREAD

**Discussion by at-Duke** [netbox-community/netbox-docker#1179] [Getting Help]
### Current Behavior

While accessing our netbox instance over traefik following error occurs on page "/ipam/ip-addresses/"

![image](https://github.com/netbox-community/netbox-docker/assets/93646814/aabd30b7-7ade-4093-8279-7bd677f11caa)

### Expected Behavior

I expected this should show ip addresses table.

### Docker Compose Version

podman-compose version: 1.0.6

### Docker Version

```text
Client:       Podman Engine
Version:      4.8.3
API Version:  4.8.3
Go Version:   go1.21.5
Built:        Wed Jan  3 14:11:40 2024
OS/Arch:      linux/amd64
```

### The git Revision

f1ca9ab7ebc16b288fd9da8825176c75d6b7ea4f

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

podman-compose -f /opt/netbox/docker-compose.yml -f /opt/netbox/docker-compose.override.yml up -d

### NetBox Logs

```text
10.89.0.2 - - [29/Feb/2024:10:00:47 +0000] "GET /ipam/ip-addresses/ HTTP/1.1" 500 1649 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox.rule=Host(`netbox.de`)"
      - "traefik.http.routers.netbox.entrypoints=websecure"
      - "traefik.http.routers.netbox.service=netbox"
      - "traefik.http.routers.netbox.tls=true"
      - "traefik.http.routers.netbox.tls.certresolver=tega"
      - "traefik.http.services.netbox.loadbalancer.server.port=8080"
    environment:
      SKIP_SUPERUSER: "false"
      # SUPERUSER_API_TOKEN: ""
      SUPERUSER_EMAIL: "administrator@netbox.de"
      SUPERUSER_NAME: "administrator"
      SUPERUSER_PASSWORD: "password"

networks:
  traefik:
    external: true
```
