### DISCUSSION TITLE
Container Image Tags are not working as listed in the README

### DISCUSSION THREAD

**Discussion by peterge-misoft** [netbox-community/netbox-docker#1198] [Getting Help] [answered]
Hey, I am just facing a problem with the version scheme of the container image tags. I am not completely sure if I am just misunderstanding sth or if there is a problem with netbox-docker.

The Readme writes [this](https://github.com/netbox-community/netbox-docker/blob/f1ca9ab7ebc16b288fd9da8825176c75d6b7ea4f/README.md?plain=1#L65):

> We recommend to use either the vX.Y.Z-a.b.c tags or the vX.Y-a.b.c tags in production!

So I use these lines in my docker-compose.override.yml:
```
  netbox:
    image: docker.io/netboxcommunity/netbox:${VERSION-v3.7-2.8.0}
  netbox-housekeeping:
    image: docker.io/netboxcommunity/netbox:${VERSION-v3.7-2.8.0}
  netbox-worker:
    image: docker.io/netboxcommunity/netbox:${VERSION-v3.7-2.8.0}
```
I understand this, to alway use the latest 3.7.X version of netbox with netbox-docker 2.8.0.

1. Tonight 3.7.5 came out, and after I executed `docker compose pull` & `docker compose up -d`, the version was still on 3.7.4.
2. So i switched all 3 lines to `${VERSION-latest-2.8.0}`, executed `docker compose pull` & `docker compose up -d` and my instance was on 3.7.5.
3. But after I changed those 3 lines back to `${VERSION-v3.7-2.8.0}` and executed `docker compose pull` & `docker compose up -d`, my instance was back on 3.7.4.

Why?
If I see it correctly, the `vX.Y-a.b.c` version tags are not working correctly. Am I overseeing sth?
