### DISCUSSION TITLE
Network overwriting and how to stop automigration

### DISCUSSION THREAD

**Discussion by ji-podhead** [netbox-community/netbox-docker#1290] [Getting Help]
### How can I add a network that doesn't have the Netbox prefix?                
The problem here is that Netbox-Docker always uses this prefix to generate the network, but in the overwrite file it uses the string (of your network name) that you provided and later adds the prefix. 
So if I want to use a network that is not created in the Compose file, I would need to give it the prefix, but when I pass it to the overwrite, I would need to split the name of my network at the prefix? I also noticed that I can overwrite the network that is created. Is it okay to do so?

### Can I stop the auto migration in the main Netbox container,                                                                                                                                                                                                          

so I don't need to delay further Ansible tasks or wait for the process to finish, or do I need to use something like this:"
```yaml
    - name: Starte Prozesse asynchron
      containers.podman.podman_container_exec: 
        name: netbox-docker_netbox_1
        user: root
        argv:
          - /bin/sh
          - -c
          - |
            process=$(ps -aux | grep manage.py | grep python3 | grep -v grep -q && echo "found process")
            echo $process        
            if([ -n "$process" ]); then
            source /opt/netbox/venv/bin/activate;
            DJANGO_SUPERUSER_PASSWORD={{password}} && python3 /opt/netbox/netbox/manage.py createsuperuser --no-input --username {{user}}  --email {{email}}
            fi
      register: result
      until: result.stdout == "\n" 
      retries: 30
      delay: 2 
```

maybe theres a more elegant way of doing this.
i hope i dont bother you with stupid question and greetings from berlin<3!
