### DISCUSSION TITLE
Docker Swarm Deployment

### DISCUSSION THREAD

**Discussion by XaratosS** [netbox-community/netbox-docker#1321] [Getting Help]
Hello community,

I am currently planning to deploy netbox to a docker swarm cluster. The cluster itself has three masters and five workers. 
Is there a possibility to create a docker compose or do I have to push the built image to a local registry and overwrite the environment variables in a diffrent compose? 

I hope this is not a silly question and maybe somebody has an idea or a clue for me to figure this issue out. 

Thanks!

**Comment by XaratosS** [comment]
So following is happening here: 

depends_on is being ignored and the netbox-worker fails, because it gets started before the netbox. After that it wont start. So far I got everything running in a Swarm besides the netbox-worker. 

You also have to set up volumes and copy the config to a share. I personally used NFS shares for this. If somebody stumbles around this, feel free to ask for details.

**Comment by astor99** [comment]
I did so:
I cloned the repository.
I created a docker-compose.override.yml

```
services:
  netbox:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.netbox-http.rule=Host(`xxxxxxxxx`)
        - traefik.http.routers.netbox-http.entrypoints=http
        - traefik.http.routers.netbox-http.middlewares=https-redirect
        - traefik.http.routers.netbox-https.rule=Host(`xxxxxxxxxxx`)
        - traefik.http.routers.netbox-https.entrypoints=https
        - traefik.http.routers.netbox-https.tls=true
        - traefik.http.routers.netbox-https.tls.certresolver=le
        - traefik.http.services.netbox.loadbalancer.server.port=8080
        
    networks:
        - traefik-public
        - netbox-network
networks:
    netbox-network:
        attachable: true
    traefik-public:
        external: true
```

I modified the docker-compose.yml to:

```
services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:${VERSION-v4.1-3.0.2}
    depends_on:
      - postgres
      - redis
      - redis-cache
    #env_file: env/netbox.env
    environment:
      CORS_ORIGIN_ALLOW_ALL: 'true'
      DB_HOST: postgres
      DB_NAME: netbox
      DB_PASSWORD: xxxxxxxxx
      DB_USER: netbox
      EMAIL_FROM: xxxxxxxxxxx
      EMAIL_PASSWORD:
      EMAIL_PORT: 25
      EMAIL_SERVER: xxxxxxxxxxxx
      EMAIL_SSL_CERTFILE:
      EMAIL_SSL_KEYFILE:
      EMAIL_TIMEOUT: 5
      EMAIL_USERNAME: netbox
      # EMAIL_USE_SSL and EMAIL_USE_TLS are mutually exclusive, i.e. they can't both be `true`!
      EMAIL_USE_SSL: 'false'
      EMAIL_USE_TLS: 'true'
      GRAPHQL_ENABLED: 'true'
      HOUSEKEEPING_INTERVAL: 86400
      MEDIA_ROOT: /opt/netbox/netbox/media
      METRICS_ENABLED: 'false'
      REDIS_CACHE_DATABASE: 1
      REDIS_CACHE_HOST: redis-cache
      REDIS_CACHE_INSECURE_SKIP_TLS_VERIFY: 'false'
      REDIS_CACHE_PASSWORD: xxxxxxxxxx
      REDIS_CACHE_SSL: 'false'
      REDIS_DATABASE: 0
      REDIS_HOST: redis
      REDIS_INSECURE_SKIP_TLS_VERIFY: 'false'
      REDIS_PASSWORD: xxxxxxxxxx
      REDIS_SSL: 'false'
      RELEASE_CHECK_URL: https://api.github.com/repos/netbox-community/netbox/releasest
      SECRET_KEY: xxxxxxxxxxxxxx
      SKIP_SUPERUSER: 'false'
      WEBHOOKS_ENABLED: 'true'

    user: "unit:root"
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s
    volumes:
      - netbox-config:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
    networks:
      - netbox-network  
  netbox-worker:
    <<: *netbox
    depends_on:
      - netbox
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
    networks:
      - netbox-network
  
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      - netbox
    command:
      - /opt/netbox/housekeeping.sh
    healthcheck:
      test: ps -aux | grep -v grep | grep -q housekeeping || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
    networks:
      - netbox-network

  # postgres
  postgres:
    image: docker.io/postgres:16-alpine
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    #env_file: env/postgres.env
    environment:
      POSTGRES_DB: netbox
      POSTGRES_PASSWORD: xxxxxxxxxx
      POSTGRES_USER: netbox

    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    networks:
      - netbox-network
      
  # redis
  redis:
    image: docker.io/valkey/valkey:8.0-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: &redis-healthcheck
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    #env_file: env/redis.env
    environment:
      REDIS_PASSWORD: xxxxxxxxxx
    volumes:
      - netbox-redis-data:/data
    networks:
      - netbox-network
  
  redis-cache:
    image: docker.io/valkey/valkey:8.0-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: *redis-healthcheck
    #env_file: env/redis-cache.env
    environment:
      REDIS_PASSWORD: xxxxxxxxxxxxxx
    volumes:
      - netbox-redis-cache-data:/data
    networks:
      - netbox-network

networks:
    netbox-network:
    
    
volumes:
  netbox-config:
    driver: to_adapt
    name: "path/netbox"
  netbox-media-files:
    driver: to_adapt
    name: "path/netbox/media"
  netbox-postgres-data:
    driver: to_adapt
    name: "path/netbox/postgres-data"
  netbox-redis-cache-data:
    driver: to_adapt
    name: "path/netbox/redis-cache-data"
  netbox-redis-data:
    driver: to_adapt
    name: "path/netbox/redis-data"
  netbox-reports-files:
    driver: to_adapt
    name: "path/netbox/reports-data"
  netbox-scripts-files:
    driver: to_adapt
    name: "path/netbox/scripts-data"
```
