### DISCUSSION TITLE
Configure ALLOWED_HOSTS - where?

### DISCUSSION THREAD

**Discussion by knebb** [netbox-community/netbox-docker#1342] [Getting Help]
Hi,

I am testing the docker image of Netbox.
By default it allows only connections to localhost. :(
`docker-compose.override.yml`:
```
services:
  netbox:
    ports:
      - "8800:8880"
```
Access is only possible through `localhost`:
```
root@docker:/srv/netbox-docker# nmap localhost -p8800
Starting Nmap 7.93 ( https://nmap.org ) at 2024-10-27 20:04 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000039s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE
8800/tcp open  sunwebadmin

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

root@docker:/srv/netbox-docker# nmap netbox.domain.local  -p8800
Starting Nmap 7.93 ( https://nmap.org ) at 2024-10-27 20:05 CET
Nmap scan report for netbox2.knebb.de (192.168.1.2)
Host is up.
rDNS record for 192.168.0.32: docker.domain.local

PORT     STATE    SERVICE
8800/tcp filtered sunwebadmin

Nmap done: 1 IP address (1 host up) scanned in 2.09 seconds
```
Added a `docker-compose.override.env`:
```
ALLOWED_HOSTS=[ '*']
```
Edited `env/netbox.env`:
```
[...]
ALLOWED_HOSTS=[ '*']
```

Edited the above .yml file:
```
services:
  netbox:
    ports:
      - "8800:8880"
    environment:
      ALLOWED_HOSTS: "[ '*' ]"
```

None of these attemps worked out- always only from localhost is accepted.

Where do I have to add the configuration value so it is taken into account?

Thanks!

/KNEBB
