### DISCUSSION TITLE
superuser creation failed via docker-compose.override.yml file

### DISCUSSION THREAD

**Discussion by Udayendu** [netbox-community/netbox-docker#1445] [Getting Help]
### Current Behavior

It's not creating the superuser when the information are passed via the `docker-compose.override.yml` file like:
```
services:
  netbox:
    ports:
      - 8000:8080
    healthcheck:
      start_period: 300s  
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_NAME: "NetBox Admin User"
      SUPERUSER_USERNAME: "admin"
      SUPERUSER_PASSWORD: "xxxxxxxxxxxxxxxx" 
```

And I can see the following logs on the console:

```
netbox-1               | Completed.
netbox-1               | ️ loadeted config '/etc/netbox/config/configuration.py'
netbox-1               |  loadeled config '/etc/netbox/config/extra.py'
netbox-1               |  loadeled config '/etc/netbox/config/logging.py'
netbox-1               |  loadeted config '/etc/netbox/config/plugins.py'
netbox-1               | 💡oSuperuser Username: NetBox Admin User, E-Mail: admin@example.com
netbox-1               | 💡oloaded config '/etc/nbob/c/config/configuration.py'
netbox-1               |  loaded cpronfig '/etc/netbox/config/extra.py'
netbox-1               |  loaded config '/etc/netbox/c fonfig/logging.py'
netbox-1               | 💡 loaded config '/etc/netbox/config/plugins.py'
netbox-1               | ️ Woarning: You have the old default admin API token in your database. This token is widely known; please remove it. Log in as your superuser and check API Tokens in your user menu.
netbox-1               | ️ Initialisation is done.
netbox-1               | ⏳oWaiting for control socket to be created... (1/10)
netbox-1               | 2025/04/02 08:42:12 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-1               | ️2025/04/02 08:42:12 [info] 7#7 unit 1.34.1 started
netbox-1               | 2025/04/02 08:42:12 [info] 429#429 discovery started
netbox-1               | 2025/04/02 08:42:12 [notice] 429#429 module: python 3.12.3 "/usr/lib/unit/modules/python3.12.unit.so"
netbox-1               | 2025/04/02 08:42:12 [info] 7#7 controller started
netbox-1               | 2025/04/02 08:42:12 [info] 431#431 router started
netbox-1               | 2025/04/02 08:42:12 [notice] 7#7 process 429 exited with code 0
netbox-1               | 2025/04/02 08:42:12 [info] 431#431 OpenSSL 3.0.13 30 Jan 2024, 300000d0
netbox-1               | ️ Applying2 configuration from /etc/unit/nginx-unit.json
netbox-1               | ️️2025/04/02 08:42:13 [info] 441#441 "netbox" prototype started
netbox-1               | 2025/04/02 08:42:13 [info] 442#442 "netbox" application started
netbox-1               |  Unit configuration loaded successfully
netbox-1               | ️️2025/04/02 08:42:14 [notic ]u7#7 process 427 exited with code 0
netbox-1               | ️️2025/04/02Y08:42:17e[info] 476#476 "netbox" application started
```

But the user is not getting created. And if I am using `docker compose exec netbox /opt/netbox/netbox/manage.py createsuperuser` command, then able to create the same user with same credentials.

### Expected Behavior

As per the documentation, it should be able to create the user.

### Docker Compose Version

Docker Compose version v2.34.0

### Docker Version

```text
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48
 Go version:        go1.23.7
 Git commit:        b8034c0
 Built:             Tue Mar 25 15:07:22 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.4
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.7
  Git commit:       6430e49
  Built:            Tue Mar 25 15:07:22 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

0b70f722f91cf90e5fa0178f3db84d28517e191d

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

docker compose up

### NetBox Logs

```text
netbox-1               | Completed.
netbox-1               | ️ loadeted config '/etc/netbox/config/configuration.py'
netbox-1               |  loadeled config '/etc/netbox/config/extra.py'
netbox-1               |  loadeled config '/etc/netbox/config/logging.py'
netbox-1               |  loadeted config '/etc/netbox/config/plugins.py'
netbox-1               | 💡oSuperuser Username: NetBox Admin User, E-Mail: admin@example.com
netbox-1               | 💡oloaded config '/etc/nbob/c/config/configuration.py'
netbox-1               |  loaded cpronfig '/etc/netbox/config/extra.py'
netbox-1               |  loaded config '/etc/netbox/c fonfig/logging.py'
netbox-1               | 💡 loaded config '/etc/netbox/config/plugins.py'
netbox-1               | ️ Woarning: You have the old default admin API token in your database. This token is widely known; please remove it. Log in as your superuser and check API Tokens in your user menu.
netbox-1               | ️ Initialisation is done.
netbox-1               | ⏳oWaiting for control socket to be created... (1/10)
netbox-1               | 2025/04/02 08:42:12 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-1               | ️2025/04/02 08:42:12 [info] 7#7 unit 1.34.1 started
netbox-1               | 2025/04/02 08:42:12 [info] 429#429 discovery started
netbox-1               | 2025/04/02 08:42:12 [notice] 429#429 module: python 3.12.3 "/usr/lib/unit/modules/python3.12.unit.so"
netbox-1               | 2025/04/02 08:42:12 [info] 7#7 controller started
netbox-1               | 2025/04/02 08:42:12 [info] 431#431 router started
netbox-1               | 2025/04/02 08:42:12 [notice] 7#7 process 429 exited with code 0
netbox-1               | 2025/04/02 08:42:12 [info] 431#431 OpenSSL 3.0.13 30 Jan 2024, 300000d0
netbox-1               | ️ Applying2 configuration from /etc/unit/nginx-unit.json
netbox-1               | ️️2025/04/02 08:42:13 [info] 441#441 "netbox" prototype started
netbox-1               | 2025/04/02 08:42:13 [info] 442#442 "netbox" application started
netbox-1               |  Unit configuration loaded successfully
netbox-1               | ️️2025/04/02 08:42:14 [notic ]u7#7 process 427 exited with code 0
netbox-1               | ️️2025/04/02Y08:42:17e[info] 476#476 "netbox" application started
```

### Content of docker-compose.override.yml

```yaml
services:
  netbox:
    ports:
      - 8000:8080
    healthcheck:
      start_period: 240s  
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_NAME: "NetBox Admin User"
      SUPERUSER_USERNAME: "admin"
      SUPERUSER_PASSWORD: "xxxxxxxxxxxxxxxx"
```

**Comment by tobiasge** [comment]
It should look like this:

```yaml
services:
  netbox:
    ports:
      - 8000:8080
    healthcheck:
      start_period: 300s  
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "xxxxxxxxxxxxxxxx" 
```
