### DISCUSSION TITLE
Need help installing via Portainer/Docker Compose

### DISCUSSION THREAD

**Discussion by begunfx** [netbox-community/netbox-docker#1461] [Getting Help]
Hi all.  I use Portainer to deploy my compose files.  I'm trying to get netbox to install but it's failing.

I'm getting the following message:
`Failed to deploy a stack: Compose up operation failed: dependency failed to start: netbox-netbox-1 exited (1)`

Any help would be greatly appreciated!

Here's my compose file (note: the .env files are replaced with environment variables since I'm using the community edition and cannot use relative paths):

```
services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:${VERSION-v4.3-3.3.0}
    depends_on:
      - postgres
      - redis
      - redis-cache
    user: "1034:100"
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s
    volumes:
      - /volume1/docker/netbox/config:/etc/netbox/config:rw
      - /volume1/docker/netbox/media:/opt/netbox/netbox/media:rw
      - /volume1/docker/netbox/reports:/opt/netbox/netbox/reports:rw
      - /volume1/docker/netbox/scripts:/opt/netbox/netbox/scripts:rw
  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/housekeeping.sh
    healthcheck:
      test: ps -aux | grep -v grep | grep -q housekeeping || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s

  # postgres
  postgres:
    image: docker.io/postgres:17-alpine
    container_name: netbox-postgres
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    volumes:
      - /volume1/docker/netbox/postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: docker.io/valkey/valkey:8.1-alpine
    container_name: netbox-redis
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: &redis-healthcheck
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    volumes:
      - /volume1/docker/netbox/redis-data:/data
  redis-cache:
    image: docker.io/valkey/valkey:8.1-alpine
    container_name: netbox-redis-cache
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: *redis-healthcheck
    volumes:
      - /volume1/docker/netbox/redis-cache-data:/data
      ```
