### DISCUSSION TITLE
LDAP config not load

### DISCUSSION THREAD

**Discussion by rbr-acs** [netbox-community/netbox-docker#1467] [Getting Help]
### Current Behavior

Hi,

LDAP Authentication not working, i checked the logs from AD the is no request from netbox. No firewall or other.

the ldap config was not loaded "/etc/netbox/config/ldap/"

```
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
```

### Expected Behavior

working ldap auth

### Docker Compose Version

Docker Compose version v2.36.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           28.2.2
 API version:       1.50
 Go version:        go1.24.3
 Git commit:        e6534b4
 Built:             Fri May 30 12:07:26 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.2.2
  API version:      1.50 (minimum version 1.24)
  Go version:       go1.24.3
  Git commit:       45873be
  Built:            Fri May 30 12:07:26 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

477decd80af739e1eaa03c20a9ccd3ddd699818a

### The git Status

```text
Auf Branch release
Ihr Branch ist auf demselben Stand wie 'origin/release'.
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
netbox-1  | ↩️ Skip creating the superuser
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1  | 144 objects imported automatically (use -v 2 for details).
netbox-1  |
netbox-1  | ✅ Initialisation is done.
netbox-1  | ⏳ Waiting for control socket to be created... (1/10)
netbox-1  | 2025/06/19 11:55:06 [warn] 8#8 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-1  | 2025/06/19 11:55:06 [info] 8#8 unit 1.34.2 started
netbox-1  | 2025/06/19 11:55:06 [info] 109#109 discovery started
netbox-1  | 2025/06/19 11:55:06 [notice] 109#109 module: python 3.12.3 "/usr/lib/unit/modules/python3.12.unit.so"
netbox-1  | 2025/06/19 11:55:06 [info] 8#8 controller started
netbox-1  | 2025/06/19 11:55:06 [notice] 8#8 process 109 exited with code 0
netbox-1  | 2025/06/19 11:55:06 [info] 111#111 router started
netbox-1  | 2025/06/19 11:55:06 [info] 111#111 OpenSSL 3.0.13 30 Jan 2024, 300000d0
netbox-1  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-1  | 2025/06/19 11:55:07 [info] 114#114 "netbox" prototype started
netbox-1  | 2025/06/19 11:55:07 [info] 115#115 "netbox" application started
netbox-1  | ✅ Unit configuration loaded successfully
netbox-1  | 2025/06/19 11:55:09 [notice] 8#8 process 107 exited with code 0
netbox-1  | 2025/06/19 11:55:09 [info] 149#149 "netbox" application started
netbox-1  | ::1 - - [19/Jun/2025:11:55:14 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:55:22 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:55:25 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:55:40 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:55:55 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:56:10 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | ::1 - - [19/Jun/2025:11:56:25 +0200] "GET /login/ HTTP/1.1" 200 3407 "-" "curl/8.5.0"
netbox-1  | 2025/06/19 11:56:33 [notice] 8#8 process 110 exited with code 0
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1  | 2025/06/19 11:56:33 [notice] 8#8 process 111 exited with code 0
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1  | 2025/06/19 11:56:38 [notice] 114#114 app process 115 exited with code 0
netbox-1  | 2025/06/19 11:56:38 [alert] 114#114 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
netbox-1  | 2025/06/19 11:56:38 [notice] 114#114 app process 149 exited with code 0
netbox-1  | 2025/06/19 11:56:38 [alert] 114#114 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
netbox-1  | 2025/06/19 11:56:38 [notice] 8#8 process 114 exited with code 0
netbox-1  | ↩️ Skip creating the superuser
netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1  | 144 objects imported automatically (use -v 2 for details).
```

### Content of docker-compose.override.yml

```yaml
services:
  netbox:
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldaps://#######"
      AUTH_LDAP_BIND_DN: "CN=sa_####,OU=####,DC=####,DC=###"
      AUTH_LDAP_BIND_PASSWORD: "####"
      AUTH_LDAP_USER_SEARCH_BASEDN: "DC=###,DC=###"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "DC=###,DC=##"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=####,OU=####,DC=####,DC=###"
      AUTH_LDAP_GROUP_TYPE: "NestedGroupOfNamesType"
      AUTH_LDAP_IS_ADMIN_DN: "CN=###,OU=###,DC=###,DC=###"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=Domänen-Admins,CN=Users,DC=####,DC=###"
      LDAP_IGNORE_CERT_ERRORS: "true"
    ports:
      - 8000:8080
    restart: unless-stopped
  netbox-worker:
    restart: unless-stopped
  netbox-housekeeping:
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped
```
