### DISCUSSION TITLE
Nginx.conf

### DISCUSSION THREAD

**Discussion by barmalej1** [netbox-community/netbox-docker#430] [Getting Help] [answered]
I have a heavily customized Nginx in my current installation. In all versions before 2.10, I could modify nginx.conf directly. Since nginx is now integrated with Netbox container how can I migrate all the setting into version 2.10+?

**Comment by tobiasge** [comment, marked as answer]
You can override the file `nginx-unit.json` in `/etc/unit/`, but this has a different format. The documentation can be found [here](https://unit.nginx.org/configuration/).

Unit doesn't have all the capabilities of nginx. So if you need additional options you will have to use nginx.

**Comment by jphernandez1587** [comment]
Hi @barmalej1. I also used a custom nginx.conf to use https://domain/netbox/ as context root for accessing the application, but I can't get that working in the new Netbox version using Unit. Did you have by chance a similar problem and know how to solve it?
The error I get is:

Static Media Failure
The following static media file failed to load: bootstrap-3.4.1-dist/css/bootstrap.min.css

Check the following:

- manage.py collectstatic was run during the most recent upgrade. This installs the most recent iteration of each static file into the static root path.
- The HTTP service (e.g. nginx or Apache) is configured to serve files from the STATIC_ROOT path. Refer to the installation documentation for further guidance.
      STATIC_URL: /netbox/static/
- The file bootstrap-3.4.1-dist/css/bootstrap.min.css exists in the static root directory and is readable by the HTTP process.

I added "/netbox" to the routes section in the nginx-unit.json as follows, but it didn't work: 

`"routes": [
    {
      "match": {
        "uri": "/netbox/static/*"
      },
      "action": {
        "share": "/opt/netbox/netbox"
      }
    },
`

Any suggestions?

**Reply by barmalej1** [reply]
the correct pass is /opt/netbox/netbox/static/bootstrap-3.4.1-dist/css/bootstrap.min.css, the section should look like this:

"routes": [ { "match": { "uri": "/static/*" }, "action": { "share": "/opt/netbox/netbox" } }, 

or 

"routes": [ { "match": { "uri": "/netbox/static/*" }, "action": { "share": "/opt/netbox" } }

**Reply by jphernandez1587** [reply]
Thanks @barmalej1 `"routes": [ { "match": { "uri": "/netbox/static/*" }, "action": { "share": "/opt/netbox" } }` did the trick :)

**Reply by barmalej1** [reply]
I added the following to docker-compose.override.yml:

```
version: '3.4'
services:
  netbox:
    volumes:
    - netbox-unit-config:/etc/unit/:ro
volumes:
  netbox-unit-config:
    driver: local
```

Then `nginx-unit.json` can be found and modified here: `/var/lib/docker/volumes/netbox-docker_netbox-unit-config/_data/`

**Reply by cimnine** [reply]
Small trick: You should be able to mount the file directly. Then you don't have to 'guess' where on the filesystem Docker puts it's volumes.

```yml
# docker-compose.override.yml
version: '3.4'
services:
  netbox:
    volumes:
    - ./your_nging_unit_configuration.json:/etc/unit/nginx-unit.json:ro
volumes:
  netbox-unit-config:
    driver: local
```
