### DISCUSSION TITLE
No 101 user in 3.0.3 image?

### DISCUSSION THREAD

**Discussion by carloscarnero** [netbox-community/netbox-docker#585] [Getting Help] [answered]
When upgrading to 3.0.2 under Kubernetes, the pod crash-loops, and this are the very last lines of the `netbox` container logs:

```
▶️  Running the startup script /opt/netbox/startup_scripts/300_circuits.py
▶️  Running the startup script /opt/netbox/startup_scripts/320_services.py
▶️  Running the startup script /opt/netbox/startup_scripts/330_power_panels.py
▶️  Running the startup script /opt/netbox/startup_scripts/340_power_feeds.py
✅ Initialisation is done.
⏳ Waiting for control socket to be created... (1/10)
2021/09/18 14:54:49 [alert] 8#8 getpwnam("101") failed, user "101" not found
```

Is this related to #546? This is was not happening with 3.0.1.

Please note that I'm using the LDAP image variant in an air-gapped environment, and this is part of the pod spec:

```yaml
spec:
  containers:
  - name: redis
    imagePullPolicy: Always
    image: example.com/redis:6.2.4
  - name: netbox
    imagePullPolicy: Always
    image: example.com/netbox:v3.0.2-ldap
    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
    envFrom:
    - configMapRef:
        name: netbox
```

The manifests have been in use for some time now, including upgrading.

**EDIT**: added the note about the image variant and a fragment of the `Deployment` object.

**Comment by lethargosapatheia** [comment]
I can confirm that the issue occurs with version `3.0.2` also. I thought the problem was related to the way I'm deploying it, but I'm glad you've posted this.

**Comment by rehashedsalt** [comment]
I know you've already seen it @carloscarnero, but I should mention that I anticipate this is a bug that snuck in as a result of #546. I filed #586 for it.

**Reply by carloscarnero** [reply]
> I know you've already seen it @carloscarnero, but I should mention that I anticipate this is a bug that snuck in as a result of #546. I filed #586 for it.

I was just replying to @lethargosapatheia with the issue you've opened 😊

**Comment by haxorof** [comment]
I can confirm that netbox 3.0.2 worked before release of netbox-docker 1.4.0. Today I tested to upgrade from working netbox 3.0.2 + netbox-docker 1.3.0 to netbox 3.0.3 + netbox-docker 1.4.0 (digest: 720bc808e53d) and that gives me the same error described in this discussion.

**Comment by kkthxbye-code** [comment, marked as answer]
You need to make sure the container entrypoint is executed as user 101. @haxorof confirmed that it was the issue he faced in #586.

I'm not that familiar with Kubernetes, but I believe you should configure it with a securityContext:

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

`runAsUser: 101` might suffice.

**Reply by carloscarnero** [reply]
I confirm that when setting the user to run as, `3.0.3-ldap`, which was released yesterday, works as expected. The following is the relevant snippet from `spec.template.spec` in the deployment manifest:

```yaml
securityContext:
  runAsUser: 101
  runAsGroup: 0
```

I went ahead and set the group as well, as per #546.
