### DISCUSSION TITLE
Plugin development

### DISCUSSION THREAD

**Discussion by rizlas** [netbox-community/netbox-docker#746] [Getting Help]
Hi,
I was reworking my netbox docker setup but I found some difficulties to understand the wiki section about plugins. In particular it only mention how to import a plugin that is already on PyPi (https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins), but what if I'm developing my own without publishing it? Currently I have a custom docker file that place plugin projects inside `/opt/netbox/netbox`. This works, even without running `setup.py install` command.

Another confusing thing is the presence of plugins settings. In wiki it is stated to use `configuration.py` and I'm using it, but here is also a `plugins.py` file. Which is the main difference here?

During plugin developing things becomes a bit messy, I looked around in other repos and people are countering in different ways (mostly building their own docker image). My current setup is a docker-compose override that mount my plugin project folder as a bind volume inside `/opt/netbox/netbox` and overrides user and command statement, but the main image is always the official netbox-docker.

**_Compose updated: 14/01/2024_**
**_This setup is also valid for reports and scripts._**

## Dockerfile:

```Dockerfile
FROM netboxcommunity/netbox:v3.6.8-2.7.0

COPY a_plugin_root_folder/a_plugin ./a_plugin

COPY ./externals_plugins.txt /tmp
RUN /opt/netbox/venv/bin/pip install --no-warn-script-location -r /tmp/externals_plugins.txt

# Custom install and plugin addition
# This SECRET_KEY is only used during the installation. There's no need to change it.
RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/netbox/manage.py collectstatic --no-input
```
## Directory tree:

```bash
netbox
├── Dockerfile
├── external_libraries.txt
├── external_plugins.txt
└── netbox-plugin-interface-sync
    ├── docs
    │   └── images
    │       ├── 1_device_page.png
    │       └── 2_interface_comparison.png
    ├── netbox_interface_sync
    │   ├── comparison.py
    │   ├── forms.py
    │   ├── __init__.py
    │   ├── template_content.py
    │   ├── templates
    │   │   └── netbox_interface_sync
    │   │       ├── compare_components_button.html
    │   │       ├── components_comparison.html
    │   │       └── number_of_interfaces_panel.html
    │   ├── urls.py
    │   ├── utils.py
    │   └── views.py
    ├── README.md
    ├── README_ru.md
    └── setup.py
```
## Docker-compose:

```yaml
x-netbox-common: &common
    image: custom_netbox_image
    restart: unless-stopped
    user: "0:0" # root user, without it setup.py develop will not work
    networks:
      - netbox
    tty: true
    env_file:
      - env/netbox.env
    volumes:
      - ./reports:/opt/netbox/netbox/reports:rw
      - ./scripts:/opt/netbox/netbox/scripts:rw
      - ./a_plugin_root_folder/a_plugin:/opt/netbox/netbox/a_plugin

version: "3.4"

services:
  netbox:
    <<: *common
    container_name: netbox
    command: >
      sh -c "/opt/netbox/venv/bin/python setup.py develop || true &&
      /opt/netbox/venv/bin/python manage.py makemigrations &&
      /opt/netbox/venv/bin/python manage.py migrate &&
      /opt/netbox/venv/bin/python manage.py createsuperuser --noinput --username local_admin --email local_admin@admin.com || true &&
      /opt/netbox/venv/bin/python manage.py runserver 0.0.0.0:8080"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=supersecretpassword
    ports:
      - 8080:8080

  netbox-worker:
    <<: *common
    container_name: netbox-worker

  netbox-housekeeping:
    <<: *common
    container_name: netbox-housekeeping
```
> [!WARNING]  
> Do not use this docker compose override in production

With this approach I achieved a fully working dev environment with auto reload and will also extract migration files that may be generated. Right now I was wondering: "What if I have to develop another plugin? Is this the right way?"

For clarification here is my directory tree inside `/opt/netbox/netbox`:
Atm I cannot put another setup.py from another custom plugin.

```
-rw-rw-r--    1 root     root            38 Dec  9 10:31 README.md (PLUGIN RELATED)
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 circuits
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 dcim
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 extras
-rwxr-xr-x    1 root     root           277 Jan  7 05:51 generate_secret_key.py
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 ipam
-rwxr-xr-x    1 root     root           249 Jan  7 05:51 manage.py
drwxrwxr-x    4 unit     root          4096 Apr 12 10:09 media
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 netbox
drwxrwxr-x    7 root     root          4096 Apr 12 08:57 netbox_plugin_hardware_assignments  (PLUGIN RELATED)
drwxr-xr-x    1 root     root          4096 Jan  7 05:51 project-static
drwxr-xr-x    2 root     root          4096 Jan  7 05:51 reports
drwxr-xr-x    2 root     root          4096 Jan  7 05:51 scripts
-rw-rw-r--    1 root     root           429 Dec  9 10:31 setup.py  (PLUGIN RELATED)
drwxr-xr-x   11 root     root          4096 Jan  7 05:57 static
drwxr-xr-x   17 root     root          4096 Jan  7 05:51 templates
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 tenancy
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 users
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 utilities
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 virtualization
drwxr-xr-x    1 root     root          4096 Jan  7 05:57 wireless
```

**Comment by rizlas** [comment]
Bump

**Reply by ryanmerolle** [reply]
I am doing something similar for now, but with tight vscode integration using the devcontainer function.  https://github.com/ryanmerolle/netbox-access-lists

**Reply by ddibenedetto** [reply]
Hi Ryan,
I'm a beginner, so I apologize in advance if the question may sounds stupid. I cloned your repo and vscode integration seems to work as expected:  according to docker-compose.yml in devcontainer, 3 containers are running.
The problem is that seems there's no a running process listening at 0.0.0.0:8000, and if I try to start the web server inside the container I get a plugin related error.
Any hint?

python3 manage.py runserver 0.0.0.0:8000
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 655, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_acls'

**Reply by mr1716** [reply]
Did you ever find a solution to this?

**Reply by Zorlin** [reply]
If it helps any, on the latest Netbox it's a different version of Python... I'm having a go now...

**Comment by ledgley** [comment]
Reloading the container each time we change a .py file takes a few minutes. Is there a faster/better approach than reloading the entire container?

**Reply by rizlas** [reply]
Have you tried my solution above?
With that you don't need to reload the entire container.

**Comment by Selfmade-RuLeZ** [comment]
Here's how I'm doing it: 

- Create a plugins folder in the root of the netbox-docker folder. 
- Clone all your development plugins in this directory. 
- Create the Dockerfile-Plugins file as shown in `1`
- Create the `docker-compose.override.yml` as shown in `2`
- Configure netbox with your plugin name in configuration.py or plugins.py
- Build and start the containers using `docker-compose build --no-cache` and `docker-compose up`
- To migrate something, you have to connect to the container using `docker exec -it <container id or name> /bin/bash` and go into the virtual env as shown in the tutorial of the plugin development guide 

I hope this helps you a little bit. 

`1`:
```dockerfile
FROM netboxcommunity/netbox:latest

# repeat the last line for every plugin you want to load editable and customize the path
COPY ./plugins /plugins
RUN /opt/netbox/venv/bin/pip install --editable /plugins/netbox-plugin-demo
```

`2`:
```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
    volumes: 
      - ./plugins:/plugins
  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
```
