### DISCUSSION TITLE
How to change Timezone from UTC to lcoal timezone?

### DISCUSSION THREAD

**Discussion by ssangho8** [netbox-community/netbox-docker#760] [Getting Help]
Hi, 
I'm trying to change time zone from UTC to KST (Asia/Seoul) showed on bottom right corner of the main page. (See attached)
I tried to change timezone settings in configuration.py to "TIME_ZONE=environ.get('TIME_ZONE', 'KST'", but this didn't work.
I need to change timezone because the time in 'change log' is different with local time.
Please help.

**Comment by ssangho8** [comment]
solved. never mind

**Comment by brammeleman** [comment]
How?

**Comment by benwa** [comment]
In `docker-compose.override.yml`:
```yml
version: '3.4'
services:
  netbox:
    environment:
      TIME_ZONE: "<TIME_ZONE>"
...
```
Replace `<TIME_ZONE>` with your [TZ database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)

**Comment by Kilthor** [comment]
I thought I would post this here for anyone else that comes across this
This is a working docker-compose.override.yml with Time Zone and GELF logging to a remote Graylog server
```
`version: "3.4"
services:
  netbox:
    environment:
      TIME_ZONE: "America/New_York"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://10.0.80.220:12201"
    ports:
    - 8001:8080
    restart: unless-stopped
  netbox-worker:
    restart: unless-stopped
  netbox-housekeeping:
    restart: unless-stopped
# Uncomment if you use NetBox Docker < 0.28.0
#  nginx:
#    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped`
```
