### DISCUSSION TITLE
Help Wanted: Deploying Netbox on Openshift

### DISCUSSION THREAD

**Discussion by MastanaGuru** [netbox-community/netbox-docker#850] [Getting Help]
Hi All,
I am working on deploying netbox on openshift 4.10. the deployment goes thru fine and the all pods are up and running, But when I access the app via the openshift route getting error
 
https://netbox-netbox.apps.ocpod.bcbsnc.com/media-failure/?filename=netbox-print.css

```
# Source: netbox/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: svc-certs
  labels:
    helm.sh/chart: netbox-4.1.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.2.8"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: netbox
---
# Source: netbox/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
  labels:
    helm.sh/chart: netbox-4.1.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.2.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netbox
      app.kubernetes.io/instance: netbox
      app.kubernetes.io/component: netbox
  template:
    metadata:
      annotations:
        checksum/config: a84478fa28e2d105e2efe44b41b10be782d37c749a374cd8d59dc9f0ff9f9100
        checksum/secret: 1a8d9fc7a875132ac588bb049ad5cfd48ea2010be8c5d053d918b82a6ef50aa6
      labels:
        app.kubernetes.io/name: netbox
        app.kubernetes.io/instance: netbox
        app.kubernetes.io/component: netbox
    spec:
      serviceAccountName: netbox
      # securityContext:
      #   fsGroup: 1000
      #   runAsNonRoot: true
      initContainers:
        - name: init-dirs
          image: "busybox:1.32.1"
          imagePullPolicy: IfNotPresent
          command: [/bin/sh, -c, mkdir -p /opt/unit/state /opt/unit/tmp]
          # securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #   readOnlyRootFilesystem: true
          #   runAsGroup: 1000
          #   runAsNonRoot: true
          #   runAsUser: 1000
          volumeMounts:
            - name: optunit
              mountPath: /opt/unit
      containers:
        - name: netbox
          # securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #   readOnlyRootFilesystem: true
          #   runAsGroup: 1000
          #   runAsNonRoot: true
          #   runAsUser: 1000
          image: "netboxcommunity/netbox:v3.2.8"
          imagePullPolicy: IfNotPresent
          env:
            - name: SUPERUSER_NAME
              value: "admin"
            - name: SUPERUSER_EMAIL
              value: "admin@example.com"
            - name: SKIP_STARTUP_SCRIPTS
              value: "true"
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /login/
          #     port: https
          #     scheme: HTTPS
          #   initialDelaySeconds: 0
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/netbox/config/configuration.py
              subPath: configuration.py
              readOnly: true
            - name: config
              mountPath: /run/config/netbox
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/netbox
              readOnly: true
            - name: netbox-tmp
              mountPath: /tmp
            - name: media
              mountPath: /opt/netbox/netbox/media
              subPath: ""
            - name: optunit
              mountPath: /opt/unit
            - name: secrets
              mountPath: /run/secrets/superuser_password
              subPath: superuser_password
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/superuser_api_token
              subPath: superuser_api_token
              readOnly: true
            - name: svc-certs
              mountPath: /etc/ssl/private
      volumes:
        - name: config
          configMap:
            name: netbox
        - name: svc-certs
          secret:
            secretName: svc-certs
            defaultMode: 384
            optional: false
        - name: secrets
          projected:
            sources:
              - secret:
                  name: "netbox"
                  items:
                    # Used by netbox-docker entry scripts
                    - key: superuser_password
                      path: superuser_password
                    - key: superuser_api_token
                      path: superuser_api_token
                    # Used by our configuration
                    - key: email_password
                      path: email_password
                    - key: napalm_password
                      path: napalm_password
                    - key: secret_key
                      path: secret_key
              - secret:
                  name: "netbox-postgresql"
                  items:
                    - key: "postgresql-password"
                      path: db_password
              - secret:
                  name: "netbox-redis"
                  items:
                    - key: "redis-password"
                      path: redis_tasks_password
              - secret:
                  name: "netbox-redis"
                  items:
                    - key: "redis-password"
                      path: redis_cache_password
        - name: netbox-tmp
          emptyDir:
            medium: Memory
        - name: optunit
          emptyDir:
            medium: Memory
        - name: media
          persistentVolumeClaim:
            claimName: netbox-media
---
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netbox
  namespace: netbox
  labels:
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v3.2.8
    helm.sh/chart: netbox-4.1.1
  annotations:
    openshift.io/host.generated: 'true'
spec:
  path: /login/
  to:
    kind: Service
    name: netbox
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```

Logs 
```
Initialisation is done.
⏳ Waiting for control socket to be created... (1/10)
2022/09/15 15:02:37 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
2022/09/15 15:02:37 [info] 7#7 unit 1.27.0 started
2022/09/15 15:02:37 [info] 145#145 discovery started
2022/09/15 15:02:37 [notice] 145#145 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
2022/09/15 15:02:37 [info] 7#7 controller started
2022/09/15 15:02:37 [notice] 7#7 process 145 exited with code 0
2022/09/15 15:02:37 [info] 147#147 router started
2022/09/15 15:02:37 [info] 147#147 OpenSSL 3.0.2 15 Mar 2022, 30000020
⚙️ Applying configuration from /etc/unit/nginx-unit.json
2022/09/15 15:02:38 [info] 151#151 "netbox" prototype started
2022/09/15 15:02:38 [info] 152#152 "netbox" application started
✅ Unit configuration loaded successfully
2022/09/15 15:02:40 [notice] 7#7 process 143 exited with code 0
2022/09/15 15:05:00 [info] 165#165 "netbox" application started
10.40.2.2 - - [15/Sep/2022:15:05:02 +0000] "GET /login/ HTTP/1.1" 200 8507 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
2022/09/15 15:07:03 [notice] 151#151 app process (isolated 165) exited with code 0
10.40.2.2 - - [15/Sep/2022:16:16:52 +0000] "-" 400 54 "-" "-"
10.40.2.2 - - [15/Sep/2022:16:16:53 +0000] "-" 400 54 "-" "-"
10.40.2.2 - - [15/Sep/2022:16:16:54 +0000] "-" 400 54 "-" "-"
10.40.2.2 - - [15/Sep/2022:16:16:55 +0000] "-" 400 54 "-" "-"
2022/09/22 19:12:47 [info] 313#313 "netbox" application started
10.41.2.2 - - [22/Sep/2022:19:12:49 +0000] "GET /login/ HTTP/1.1" 200 8599 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
2022/09/22 19:14:50 [notice] 145#145 app process (isolated 146) exited with code 0
```

css file is available
```
/opt/netbox/netbox/project-static/dist/cable_trace.css
/opt/netbox/netbox/project-static/dist/graphiql.css
/opt/netbox/netbox/project-static/dist/netbox-dark.css
/opt/netbox/netbox/project-static/dist/netbox-external.css
/opt/netbox/netbox/project-static/dist/netbox-light.css
/opt/netbox/netbox/project-static/dist/netbox-print.css
/opt/netbox/netbox/project-static/dist/rack_elevation.css
/opt/netbox/netbox/project-static/docs/assets/_mkdocstrings.css
/opt/netbox/netbox/project-static/docs/assets/stylesheets/main.2e8b5541.min.css
/opt/netbox/netbox/project-static/docs/assets/stylesheets/palette.cbb835fc.min.css
/opt/netbox/netbox/project-static/docs/extra.css
/opt/netbox/netbox/static/admin/css/autocomplete.css
/opt/netbox/netbox/static/admin/css/base.css
/opt/netbox/netbox/static/admin/css/changelists.css
/opt/netbox/netbox/static/admin/css/dashboard.css
/opt/netbox/netbox/static/admin/css/fonts.css
/opt/netbox/netbox/static/admin/css/forms.css
/opt/netbox/netbox/static/admin/css/login.css
/opt/netbox/netbox/static/admin/css/nav_sidebar.css
/opt/netbox/netbox/static/admin/css/responsive.css
/opt/netbox/netbox/static/admin/css/responsive_rtl.css
/opt/netbox/netbox/static/admin/css/rtl.css
/opt/netbox/netbox/static/admin/css/vendor/select2/select2.css
/opt/netbox/netbox/static/admin/css/vendor/select2/select2.min.css
/opt/netbox/netbox/static/admin/css/widgets.css
/opt/netbox/netbox/static/cable_trace.css
/opt/netbox/netbox/static/debug_toolbar/css/print.css
/opt/netbox/netbox/static/debug_toolbar/css/toolbar.css
/opt/netbox/netbox/static/django_tables2/bootstrap.css
/opt/netbox/netbox/static/django_tables2/themes/paleblue/css/screen.css
/opt/netbox/netbox/static/docs/assets/_mkdocstrings.css
/opt/netbox/netbox/static/docs/assets/stylesheets/main.2e8b5541.min.css
/opt/netbox/netbox/static/docs/assets/stylesheets/palette.cbb835fc.min.css
/opt/netbox/netbox/static/docs/extra.css
/opt/netbox/netbox/static/drf-yasg/style.css
/opt/netbox/netbox/static/drf-yasg/swagger-ui-dist/swagger-ui.css
/opt/netbox/netbox/static/graphiql.css
/opt/netbox/netbox/static/mptt/draggable-admin.css
/opt/netbox/netbox/static/netbox-dark.css
/opt/netbox/netbox/static/netbox-external.css
**/opt/netbox/netbox/static/netbox-light.css**
/opt/netbox/netbox/static/netbox-print.css
/opt/netbox/netbox/static/rack_elevation.css
/opt/netbox/netbox/static/rest_framework/css/bootstrap-theme.min.css
/opt/netbox/netbox/static/rest_framework/css/bootstrap-tweaks.css
/opt/netbox/netbox/static/rest_framework/css/bootstrap.min.css
/opt/netbox/netbox/static/rest_framework/css/default.css
/opt/netbox/netbox/static/rest_framework/css/font-awesome-4.0.3.css
/opt/netbox/netbox/static/rest_framework/css/prettify.css
/opt/netbox/netbox/static/rest_framework/docs/css/base.css
/opt/netbox/netbox/static/rest_framework/docs/css/highlight.css
/opt/netbox/netbox/static/rest_framework/docs/css/jquery.json-view.min.css
/opt/netbox/docs/extra.css
```
