### DISCUSSION TITLE
initialize the tags field of an object/entity

### DISCUSSION THREAD

**Discussion by sarduk** [netbox-community/netbox-docker#878] [Getting Help]
netbox from dockerhub v2.0.0

is it possible to initialize the tags field of an object/entity such as ipam / prefixes?

initializers/tags.yml
```
 - name: Tag 1
   slug: tag-1
 - name: Tag 2
   slug: tag-2

```

I tried these without success, it did not give an error, but it did not value any tags
 
initializers/prefixes.yml 
```
 - description: prefix10
   prefix: 8.53.136.40/30
   status: active

tags:
   - tag-2

tags:
   name: tag-2

```
thanks from now for answers
