### DISCUSSION TITLE
Issue deploying docker

### DISCUSSION THREAD

**Discussion by huntson** [netbox-community/netbox-docker#936] [Getting Help]
### Current Behavior

I cannot get past a certain point when deploying via Portainer.  When I copy and paste all the yaml file into a Stacks config, I get the following error:  'failed to deploy a stack: open /data/compose/34/env/netbox.env: no such file ro directory'

Each time I attempt to deploy the number goes up: 35, 36, etc

### Expected Behavior

I'd expect the Docker to deploy.

### Docker Compose Version

20.10.14

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.19.3
 Git commit:        a224086
 Built:             Mon Nov 14 19:20:50 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.3
  Git commit:       87a90dc
  Built:            Mon Nov 14 19:22:01 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

?????

### The git Status

```text
I have no clue where to enter this
```

### Startup Command

n/a

### NetBox Logs

```text
n/a
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:${VERSION-v3.4-2.4.0}
    depends_on:
    - postgres
    - redis
    - redis-cache
    env_file: env/netbox.env
    user: 'unit:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/api/ || exit 1"
    volumes:
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q housekeeping || exit 1"

  # postgres
  postgres:
    image: postgres:15-alpine
    env_file: env/postgres.env
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis-cache.env
    volumes:
    - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
```

**Comment by williamhatcher** [comment]
Howdy @huntson,

I am working on this myself. 

One thing to note is that Portainer stores all environment variables in a file called `stack.env` so you should fix the env_file lines.

Once I get a solid setup going, I'll put instructions here, and maybe in the wiki/readme.

**Comment by TOLoneWolf** [comment]
I was trying to do the same thing running netbox with portainer on my alpine vm.

The instructions are for running [netbox docker](https://github.com/netbox-community/netbox-docker) using the docker-compose.yml from the command line with their files from the github project. The project contains an env folder that has multple env files for each container it is going to start (netbox.env, postgres.env, redis.env, redis-cache.env).

so I had to figure out what what needed to be moved around because the environment variables are in a separate folder, they used merge keys, and expect you to use the docker-compose.override.yml to add your port mapping and other change it seems.

Very helpful information on **docker/yaml/portainer** to figure what the compose file was doing:
https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
https://docs.portainer.io/user/docker/stacks/add#environment-variables
https://docs.docker.com/engine/reference/builder/#healthcheck
.
.
.
Here is what I did get netbox working in a portainer stack:
- Downloaded the github project as a zip and extracted the env folder
- In portainer added a new stack with web editor 
- in the Environment variables section below clicked Load variables from .env file. Fid that for netbox.env, postgres.env, redis.env. NOT redis-cache.env since it uses the same variable name as redis.env. Changed in compose to use the correct password variable.
- Modified the docker-compose.yml to what is below
- It will take a few minutes to set everything up the first time so healthcheck will fail and stop it. I just deployed it again and it was able to finish setting up before the healthcheck. I increased the interval in the config below so it might make it all the way through the first time.
- then go to the containers open the console for netbox-netbox-1 and enter the command listed under the [quick start guide for first user setup](https://github.com/netbox-community/netbox-docker):
```
/opt/netbox/netbox/manage.py createsuperuser
```
- close connection and login to web interface with the super user just created.

docker-compose in web editor:
```yaml
version: '3.4'

x-merge-keys: &shared_settings
  restart: unless-stopped
  healthcheck:
    start_period: 60s
    timeout: 3s
    interval: 60s
    test: "curl -f http://localhost:8080/api/ || exit 1"
  image: docker.io/netboxcommunity/netbox:${VERSION-v3.4-2.5.1}
  depends_on:
  - postgres
  - redis
  - redis-cache
  env_file: 
  #- env/redis.env # For using Portainer comment out
  - stack.env # For using Portainer uncomment this line
  user: 'unit:root'
  volumes:
  #- ./configuration:/etc/netbox/config:z,ro
  #- ./reports:/etc/netbox/reports:z,ro
  #- ./scripts:/etc/netbox/scripts:z,ro
  - netbox-media-files:/opt/netbox/netbox/media:z
  # I switch to named volume and removed readonly. it normally would map to the folders seen in the root of the github project here.
  - netbox_data:/etc/netbox:z
  

services:
  netbox:
    <<: *shared_settings
    ports:
    - 8000:8080
    
  netbox-worker:
    <<: *shared_settings
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"
    
  netbox-housekeeping:
    <<: *shared_settings
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q housekeeping || exit 1"

  # postgres
  postgres:
    restart: unless-stopped
    image: docker.io/postgres:15-alpine
    env_file: 
    #- env/redis.env # For using Portainer comment out
    - stack.env # For using Portainer uncomment this line
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    restart: unless-stopped
    image: docker.io/redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: 
    #- env/redis.env # For using Portainer comment out
    - stack.env # For using Portainer uncomment this line
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    restart: unless-stopped
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    # env_file: # For using Portainer comment out
    #- env/redis.env # For using Portainer comment out
    environment: # For using Portainer uncomment this line
    - REDIS_PASSWORD=${REDIS_CACHE_PASSWORD} # For using Portainer uncomment this line
    volumes:
    - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox_data:
    driver: local
```
.
.
**Note:** Tried portainer directily using repository instead of web editor, it fails trying to find the config, scripts, reports folders and stalls portainer from  completing/failing. You would still need to get your docker-compose.override.yml in the correct location to do your port mapping as well.
also seems to prevent it from setting anything up until i restart docker.
