### DISCUSSION TITLE
Netbox Application running on docker is not working on Ubuntu 22.0.4

### DISCUSSION THREAD

**Discussion by emanuelferguson** [netbox-community/netbox-docker#949] [Getting Help]
### Current Behavior

Netbox Application is not running.  Netbox worker exited with an error "TimeoutError: [Errno 110] Connection timed out".

### Expected Behavior

Application running when docker containers start up.

### Docker Compose Version

docker-compose version 1.29.2, build unknown docker-py version: 5.0.3 CPython version: 3.6.9 OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
HEAD detached at 2.1.0
nothing to commit, working tree clean
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
Attaching to network-inventory-api_netbox_1, network-inventory-api_netbox-worker_1, network-inventory-api_redis_1, network-inventory-api_postgres_1, network-inventory-api_redis-cache_1
netbox-worker_1  | No queues have been specified. This process will service the following queues by default: high, default, low
postgres_1       |
postgres_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1       |
postgres_1       | 2023-01-06 18:09:46.570 UTC [1] LOG:  starting PostgreSQL 14.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
postgres_1       | 2023-01-06 18:09:46.571 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2023-01-06 18:09:46.571 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1       | 2023-01-06 18:09:46.580 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2023-01-06 18:09:46.597 UTC [23] LOG:  database system was shut down at 2023-01-06 18:09:34 UTC
postgres_1       | 2023-01-06 18:09:46.609 UTC [1] LOG:  database system is ready to accept connections
redis-cache_1    | 1:C 06 Jan 2023 18:09:46.724 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-cache_1    | 1:C 06 Jan 2023 18:09:46.724 # Redis version=7.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis-cache_1    | 1:C 06 Jan 2023 18:09:46.724 # Configuration loaded
redis-cache_1    | 1:M 06 Jan 2023 18:09:46.724 * monotonic clock: POSIX clock_gettime
redis-cache_1    | 1:M 06 Jan 2023 18:09:46.725 * Running mode=standalone, port=6379.
redis-cache_1    | 1:M 06 Jan 2023 18:09:46.725 # Server initialized
redis-cache_1    | 1:M 06 Jan 2023 18:09:46.726 * Ready to accept connections
redis_1          | 1:C 06 Jan 2023 18:09:46.706 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 06 Jan 2023 18:09:46.706 # Redis version=7.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 06 Jan 2023 18:09:46.706 # Configuration loaded
redis_1          | 1:M 06 Jan 2023 18:09:46.706 * monotonic clock: POSIX clock_gettime
redis_1          | 1:M 06 Jan 2023 18:09:46.708 * Running mode=standalone, port=6379.
redis_1          | 1:M 06 Jan 2023 18:09:46.708 # Server initialized
redis_1          | 1:M 06 Jan 2023 18:09:46.712 * Reading RDB base file on AOF loading...
redis_1          | 1:M 06 Jan 2023 18:09:46.715 * Loading RDB produced by version 7.0.7
redis_1          | 1:M 06 Jan 2023 18:09:46.715 * RDB age 265964 seconds
redis_1          | 1:M 06 Jan 2023 18:09:46.715 * RDB memory usage when created 0.82 Mb
redis_1          | 1:M 06 Jan 2023 18:09:46.715 * RDB is base AOF
redis_1          | 1:M 06 Jan 2023 18:09:46.715 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1          | 1:M 06 Jan 2023 18:09:46.716 * DB loaded from base file appendonly.aof.1.base.rdb: 0.004 seconds
redis_1          | 1:M 06 Jan 2023 18:09:46.716 * DB loaded from append only file: 0.005 seconds
redis_1          | 1:M 06 Jan 2023 18:09:46.716 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
redis_1          | 1:M 06 Jan 2023 18:09:46.716 * Ready to accept connections
netbox-worker_1  | Traceback (most recent call last):
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
netbox-worker_1  | ? loaded config '/etc/netbox/config/configuration.py'
netbox-worker_1  | ? loaded config '/etc/netbox/config/extra.py'
netbox-worker_1  | ? loaded config '/etc/netbox/config/logging.py'
netbox-worker_1  | ? loaded config '/etc/netbox/config/plugins.py'
netbox-worker_1  |     sock = self.retry.call_with_retry(
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/retry.py", line 51, in call_with_retry
netbox-worker_1  |     raise error
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
netbox-worker_1  |     return do()
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
netbox-worker_1  |     lambda: self._connect(), lambda error: self.disconnect(error)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
netbox-worker_1  |     raise err
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
netbox-worker_1  |     sock.connect(socket_address)
netbox-worker_1  | TimeoutError: [Errno 110] Connection timed out
netbox-worker_1  |
netbox-worker_1  | During handling of the above exception, another exception occurred:
netbox-worker_1  |
netbox-worker_1  | Traceback (most recent call last):
netbox-worker_1  |   File "/opt/netbox/netbox/manage.py", line 10, in <module>
netbox-worker_1  |     execute_from_command_line(sys.argv)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-worker_1  |     utility.execute()
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
netbox-worker_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
netbox-worker_1  |     self.execute(*args, **cmd_options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
netbox-worker_1  |     output = self.handle(*args, **options)
netbox-worker_1  |   File "/opt/netbox/netbox/extras/management/commands/rqworker.py", line 26, in handle
netbox-worker_1  |     super().handle(*args, **options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django_rq/management/commands/rqworker.py", line 122, in handle
netbox-worker_1  |     w = get_worker(*args, **worker_kwargs)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django_rq/workers.py", line 51, in get_worker
netbox-worker_1  |     return worker_class(queues,
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/rq/worker.py", line 220, in __init__
netbox-worker_1  |     connection.client_setname(self.name)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/commands/core.py", line 697, in client_setname
netbox-worker_1  |     return self.execute_command("CLIENT SETNAME", name, **kwargs)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
netbox-worker_1  |     conn = self.connection or pool.get_connection(command_name, **options)
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
netbox-worker_1  |     connection.connect()
netbox-worker_1  |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 615, in connect
netbox-worker_1  |     raise TimeoutError("Timeout connecting to server")
netbox-worker_1  | redis.exceptions.TimeoutError: Timeout connecting to server
netbox_1         | 	Is the server running on that host and accepting TCP/IP connections?
netbox_1         | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox_1         | ? Waiting on DB... (0s / 30s)
network-inventory-api_netbox-worker_1 exited with code 1
```

### Content of docker-compose.override.yml

```yaml
version: "3.3"

services:
    netbox: &netbox
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/netboxcommunity/netbox:v3.2.9
        depends_on:
            - postgres
            - redis
            - redis-cache
            - netbox-worker
        env_file: netbox/netbox-docker/env/netbox.env
        user: 'unit:root'
        volumes:
            - ./netbox/netbox-docker/startup_scripts:/opt/netbox/startup_scripts:z,ro
            - ./netbox/netbox-docker/initializers:/opt/netbox/initializers:z,ro
            - ./netbox/netbox-docker/configuration:/etc/netbox/config:z,ro
            - ./netbox/netbox-docker/reports:/etc/netbox/reports:z,ro
            - ./netbox/netbox-docker/scripts:/etc/netbox/scripts:z,ro
            - netbox-media-files:/opt/netbox/netbox/media:z
        networks:
            - default
        ports:
            - "8890:8080"
        expose:
            - 8080

    netbox-worker:
        <<: *netbox
        depends_on:
            - redis
        entrypoint:
            - /opt/netbox/venv/bin/python
            - /opt/netbox/netbox/manage.py
        command:
            - rqworker
        ports: [ ]

    # postgres for netbox
    postgres:
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/postgres:14-alpine
        env_file: netbox/netbox-docker/env/postgres.env
        volumes:
            - netbox-postgres-data:/var/lib/postgresql/data

    # redis for netbox
    redis:
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/redis:7-alpine
        command:
            - sh
            - -c # this is to evaluate the $REDIS_PASSWORD from the env
            - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
        env_file: netbox/netbox-docker/env/redis.env
        volumes:
            - netbox-redis-data:/data
    redis-cache:
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/redis:7-alpine
        command:
            - sh
            - -c # this is to evaluate the $REDIS_PASSWORD from the env
            - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
        env_file: netbox/netbox-docker/env/redis-cache.env

volumes:
    netbox-media-files:
        driver: local
    netbox-postgres-data:
        driver: local
    netbox-redis-data:
        driver: local
```
