### DISCUSSION TITLE
Cannot start netbox-docker-netbox-1 after upgrate from 3.2.5 to 3.4.5

### DISCUSSION THREAD

**Discussion by Negatifff** [netbox-community/netbox-docker#952] [Getting Help]
Hello

I'm not very good at docker - I just update the netbox docker from time to time on request. The upgrade process has never been particularly difficult...until now. I have version 3.2.5 and I want to update it to the latest 3.4.5. I also changed the postgres version from 14 to 15 along the way. I dumped the data from the database, updated the postgres, uploaded the data to the new version. It's ok. But I failed to start the netbox - the docker netbox-docker-netbox-1 constantly falls off by timeout with the message

`dependency failed to start: container netbox-docker-netbox-1 is unhealthy`

viewing logs with

`docker-compose logs -f`

shows the following:

>netbox-docker-netbox-1       | Traceback (most recent call last):
netbox-docker-netbox-1       |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-docker-netbox-1       |     execute_from_command_line(sys.argv)
netbox-docker-netbox-1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-docker-netbox-1       |     utility.execute()
netbox-docker-netbox-1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
netbox-docker-netbox-1       |     settings.INSTALLED_APPS
netbox-docker-netbox-1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
netbox-docker-netbox-1       |     self._setup(name)
netbox-docker-netbox-1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
netbox-docker-netbox-1       |     self._wrapped = Settings(settings_module)
netbox-docker-netbox-1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
netbox-docker-netbox-1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox-docker-netbox-1       |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-docker-netbox-1       |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1       |   File "/opt/netbox/netbox/netbox/settings.py", line 55, in <module>
netbox-docker-netbox-1       |     configuration = importlib.import_module(config_path)
netbox-docker-netbox-1       |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-docker-netbox-1       |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1       |   File "/opt/netbox/netbox/netbox/configuration.py", line 71, in <module>
netbox-docker-netbox-1       |     _loaded_configurations = read_configurations(
netbox-docker-netbox-1       |   File "/opt/netbox/netbox/netbox/configuration.py", line 33, in read_configurations
netbox-docker-netbox-1       |     _import(f"{config_module}.{main_config}", main_config_path, loaded_configurations)
netbox-docker-netbox-1       |   File "/opt/netbox/netbox/netbox/configuration.py", line 20, in _import
netbox-docker-netbox-1       |     spec.loader.exec_module(module)
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-docker-netbox-1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1       |   File "/etc/netbox/config/configuration.py", line 20, in <module>
netbox-docker-netbox-1       |     def _read_secret(secret_name: str, default: str | None = None) -> str | None:
netbox-docker-netbox-1       | TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
netbox-docker-netbox-1       | ⏳ Waiting on DB... (27s / 30s)
netbox-docker-netbox-1       | ❌ Waited 30s or more for the DB to become ready.

`docker-compose ps-a`
```

NAME                                  IMAGE                                COMMAND                  SERVICE               CREATED             STATUS                             PORTS
netbox-docker-netbox-1                netboxcommunity/netbox:latest-ldap   "/sbin/tini -- /opt/…"   netbox                About an hour ago   Up 25 seconds (health: starting)   0.0.0.0:8000->8080/tcp, :::8000->8080/tcp
netbox-docker-netbox-housekeeping-1   netboxcommunity/netbox:latest-ldap   "/sbin/tini -- /opt/…"   netbox-housekeeping   About an hour ago   Created
netbox-docker-netbox-worker-1         netboxcommunity/netbox:latest-ldap   "/sbin/tini -- /opt/…"   netbox-worker         About an hour ago   Created
netbox-docker-postgres-1              postgres:15-alpine                   "docker-entrypoint.s…"   postgres              About an hour ago   Up About an hour                   5432/tcp
netbox-docker-redis-1                 redis:7-alpine                       "docker-entrypoint.s…"   redis                 About an hour ago   Up About an hour                   6379/tcp
netbox-docker-redis-cache-1           redis:7-alpine                       "docker-entrypoint.s…"   redis-cache           About an hour ago   Up About an hour                   6379/tcp
```

I've already scratched my head what could be the problem. If someone can help I would be grateful.

docker-compose.yml
```
version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:${VERSION-latest-ldap}
    depends_on:
    - postgres
    - redis
    - redis-cache
    env_file: env/netbox.env
    user: 'unit:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8000/api/ || exit 1"
    volumes:
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
    - /opt/netbox/housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "ps -aux | grep -v grep | grep -q housekeeping || exit 1"

  # postgres
  postgres:
    image: postgres:15-alpine
    env_file: env/postgres.env
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis-cache.env
    volumes:
    - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis-cache-data:
    driver: local`
```

docker-compose.override.yml

```
version: '3.4'
services:
  netbox:
    image: netboxcommunity/netbox:${VERSION-latest-ldap}
    ports:
      - 8000:8080
    restart: unless-stopped
    environment:
      AUTH_LDAP_SERVER_URI: "ldap://ldap.host"
      AUTH_LDAP_USER_SEARCH_BASEDN: "ou=People,dc=xxxx,dc=xx"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "ou=group,dc=xxxx,dc=xx"
      AUTH_LDAP_REQUIRE_GROUP_DN: "cn=netbox,ou=group,dc=xxx,dc=xx" # or "cn=netbox"
      AUTH_LDAP_IS_ADMIN_DN: "cn=netbox-root,ou=group,dc=xxx,dc=xx"
      AUTH_LDAP_IS_SUPERUSER_DN: "cn=netbox-admin,ou=group,dc=xxx,dc=xx"
      AUTH_LDAP_USER_SEARCH_ATTR: "uid"
      AUTH_LDAP_GROUP_SEARCH_CLASS: "posixGroup"
      AUTH_LDAP_GROUP_TYPE: "PosixGroupType"
      AUTH_LDAP_ATTR_LASTNAME: "sn"
      AUTH_LDAP_ATTR_FIRSTNAME: "givenName"
      AUTH_LDAP_FIND_GROUP_PERMS: "true"
      AUTH_LDAP_CACHE_TIMEOUT: 3600
      LDAP_IGNORE_CERT_ERRORS: "false"
      NAPALM_USERNAME: "user"
      NAPALM_PASSWORD: "xxxx"
      NETBOX_DELETE_LEGACY_DATA: "true"
      SKIP_SUPERUSER: "true"
```

versions:

```
# docker -v
Docker version 23.0.1, build a5ee5b1
# docker-compose -v
Docker Compose version v2.16.0
```
