### ISSUE TITLE
dependency failed to start: container netbox-1 with VERSION-latest-ldap

### ISSUE THREAD

**Issue by git-inc** [netbox-community/netbox-docker#1046]
### Current Behavior

When i tried to use last-ldap docker image, a dependency failed to start: container netbox-ldap-netbox-1

version: '3.4'
services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:${VERSION-latest-ldap}

it's work fine with:   
image: docker.io/netboxcommunity/netbox:${VERSION-latest}

I have clean all containers, volumes .... it's a fresh install.

### Expected Behavior

CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                   PORTS                  NAMES
2b99fab6185c   netboxcommunity/netbox:latest   "/usr/bin/tini -- /o…"   5 minutes ago   Up 4 minutes (healthy)                          netbox-netbox-housekeeping-1
0b3708a5876f   netboxcommunity/netbox:latest   "/usr/bin/tini -- /o…"   5 minutes ago   Up 4 minutes (healthy)                          netbox-netbox-worker-1
afd282288711   netboxcommunity/netbox:latest   "/usr/bin/tini -- /o…"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:80->8080/tcp   netbox-netbox-1
60f16b8e7a29   postgres:15-alpine              "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes             5432/tcp               netbox-postgres-1
b9cc0f85143f   redis:7-alpine                  "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes             6379/tcp               netbox-redis-1
e164ce672327   redis:7-alpine                  "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes             6379/tcp               netbox-redis-cache-1

### Docker Compose Version

 v2.18.1

### Docker Version

```text
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:10 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:10 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

22486fefb5c4cc326bd091abeac5314eb7acd37f

### The git Status

```text
modified:   docker-compose.override.yml
modified:   env/netbox.env
```

### Startup Command

docker compose up

### NetBox Logs

```text
netbox-ldap-netbox-1  | ⏳ Waiting on DB... (24s / 30s)
netbox-ldap-netbox-1  | Traceback (most recent call last):
netbox-ldap-netbox-1  |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-ldap-netbox-1  |     execute_from_command_line(sys.argv)
netbox-ldap-netbox-1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-ldap-netbox-1  |     utility.execute()
netbox-ldap-netbox-1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
netbox-ldap-netbox-1  |     settings.INSTALLED_APPS
netbox-ldap-netbox-1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
netbox-ldap-netbox-1  |     self._setup(name)
netbox-ldap-netbox-1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
netbox-ldap-netbox-1  |     self._wrapped = Settings(settings_module)
netbox-ldap-netbox-1  |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
netbox-ldap-netbox-1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox-ldap-netbox-1  |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-ldap-netbox-1  |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-ldap-netbox-1  |   File "/opt/netbox/netbox/netbox/settings.py", line 55, in <module>
netbox-ldap-netbox-1  |     configuration = importlib.import_module(config_path)
netbox-ldap-netbox-1  |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-ldap-netbox-1  |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-ldap-netbox-1  |   File "/opt/netbox/netbox/netbox/configuration.py", line 71, in <module>
netbox-ldap-netbox-1  |     _loaded_configurations = read_configurations(
netbox-ldap-netbox-1  |   File "/opt/netbox/netbox/netbox/configuration.py", line 33, in read_configurations
netbox-ldap-netbox-1  |     _import(f"{config_module}.{main_config}", main_config_path, loaded_configurations)
netbox-ldap-netbox-1  |   File "/opt/netbox/netbox/netbox/configuration.py", line 20, in _import
netbox-ldap-netbox-1  |     spec.loader.exec_module(module)
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-ldap-netbox-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-ldap-netbox-1  |   File "/etc/netbox/config/configuration.py", line 20, in <module>
netbox-ldap-netbox-1  |     def _read_secret(secret_name: str, default: str | None = None) -> str | None:
netbox-ldap-netbox-1  | TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
netbox-ldap-netbox-1  | ⏳ Waiting on DB... (27s / 30s)
netbox-ldap-netbox-1  | ❌ Waited 30s or more for the DB to become ready
```

### Content of docker-compose.override.yml

```yaml
version: "3.4"
services:
  netbox:
    ports:
      - 80:8080
    image: &NetboxImage netboxcommunity/netbox:${VERSION-latest-ldap}
    environment:
      AUTH_LDAP_SERVER_URI: "ldaps://domain.com"
      AUTH_LDAP_BIND_DN: "CN=Netbox,OU=EmbeddedDevices,OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_BIND_PASSWORD: "TopSecretPassword"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=SubGroups,OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-User,OU=SoftwareGroups,OU=SubGroups,OU=MyCompany,DC=domain,dc=com"
      AUTH_LDAP_IS_ADMIN_DN: "CN=Network Configuration Operators,CN=Builtin,DC=domain,dc=com"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=Domain Admins,CN=Users,DC=domain,dc=com"
      LDAP_IGNORE_CERT_ERRORS: "false"
  netbox-worker:
    image: *NetboxImage
  netbox-housekeeping:
    image: *NetboxImage
```
