### ISSUE TITLE
Cannot delete a user account with Bookmarks

### ISSUE THREAD

**Issue by NetTech2001** [netbox-community/netbox-docker#1136]
### Current Behavior

Attempting to delete a user account that has an associated bookmark with throw a dependency error. Cannot delete account because it is dependent on "bookmarked device". Tested on Netbox v3.7.0

### Expected Behavior

I would expect that since the bookmarks are per account that deleting the account should just delete the bookmark as well, but that needs to be done prior to deleting the account.

### Docker Compose Version

2.21.0

### Docker Version

```text
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

f1ca9ab7ebc16b288fd9da8825176c75d6b7ea4f

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   configuration/configuration.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Caddyfile
        Dockerfile-Plugins
        backup/
        certs/
        docker-compose.override.yml.backup
        docker-compose.override.yml.original
        media-backup.tar.bz2
        netbox_backup.sh
        netbox_restore.sh
        plugin_requirements.txt
```

### Startup Command

docker compose up

### NetBox Logs

```text
netbox-docker-netbox-1  | ↩️ Skip creating the superuser
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-docker-netbox-1  | ⚠️ Warning: You have the old default admin token in your database. This token is widely known; please remove it.
netbox-docker-netbox-1  | ✅ Initialisation is done.
netbox-docker-netbox-1  | ⏳ Waiting for control socket to be created... (1/10)
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [info] 7#7 unit 1.31.1 started
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [info] 13#13 discovery started
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [notice] 13#13 module: python 3.11.4 "/usr/lib/unit/modules/python3.11.unit.so"
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [info] 7#7 controller started
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [notice] 7#7 process 13 exited with code 0
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [info] 15#15 router started
netbox-docker-netbox-1  | 2024/01/18 15:58:51 [info] 15#15 OpenSSL 3.0.8 7 Feb 2023, 30000080
netbox-docker-netbox-1  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-docker-netbox-1  | 2024/01/18 15:58:52 [info] 18#18 "netbox" prototype started
netbox-docker-netbox-1  | 2024/01/18 15:58:52 [info] 19#19 "netbox" application started
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-docker-netbox-1  | ✅ Unit configuration loaded successfully
netbox-docker-netbox-1  | 2024/01/18 15:58:54 [notice] 7#7 process 11 exited with code 0
netbox-docker-netbox-1  | 2024/01/18 15:58:54 [info] 28#28 "netbox" application started
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  tls:
    restart: unless-stopped
    image: caddy:latest
    depends_on:
      - netbox
    volumes:
      - ./certs/itsnetboxtest+4.pem:/etc/ssl/private/cert.crt:ro,z
      - ./certs/itsnetboxtest+4-key.pem:/etc/ssl/private/key.key:ro,z
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80 # Allows for http redirection
      - 443:443

  netbox:
    restart: unless-stopped
    ports:
      - 8000:8080
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "REDACTED"
      AUTH_LDAP_BIND_DN: "REDACTED"
      AUTH_LDAP_BIND_PASSWORD: "REDACTED"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=ITS,OU=LCC Staff,DC=lethbridgecollege,DC=ab,DC=ca"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=Domain Groups,DC=lethbridgecollege,DC=ab,DC=ca"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=NetboxUsers,OU=Domain Groups,DC=lethbridgecollege,DC=ab,DC=ca"
      AUTH_LDAP_GROUP_TYPE: "NestedActiveDirectoryGroupType"
      AUTH_LDAP_IS_ADMIN_DN: "CN=NetAdmin,OU=Domain Groups,DC=lethbridgecollege,DC=ab,DC=ca"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=NetAdmin,OU=Domain Groups,DC=lethbridgecollege,DC=ab,DC=ca"
      LDAP_IGNORE_CERT_ERRORS: "false"
      LDAP_CA_CERT_DIR:  "/etc/netbox/certs"
      LDAP_CA_CERT_FILE: "/etc/netbox/certs/LDAPS.crt"
    volumes:
    - ./certs:/etc/netbox/certs:z,ro
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins

  netbox-worker:
    restart: unless-stopped
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  netbox-housekeeping:
    restart: unless-stopped
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  redis-cache:
    restart: unless-stopped
```
