### ISSUE TITLE
using environment block  in example file fails

### ISSUE THREAD

**Issue by kifeo** [netbox-community/netbox-docker#1148]
### Current Behavior

when decomenting the example override  docker-compose file, the following error occurs : 

`expected <block end>, but found '<block mapping start>'`

### Expected Behavior

The example file should be ready when removing the comments

### Docker Compose Version

podman-compose 1.0.6

### Docker Version

```text
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.18.1
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

### The git Revision

f1ca9ab7ebc16b288fd9da8825176c75d6b7ea4f

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

podman-compose up

### NetBox Logs

```text
N/A as does not start
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - "8000:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: ""
      SUPERUSER_EMAIL: ""
      SUPERUSER_NAME: ""
      SUPERUSER_PASSWORD: ""
```
