### ISSUE TITLE
dependency failed to start: container netbox-docker-netbox-1 exited (127)

### ISSUE THREAD

**Issue by Juganooo** [netbox-community/netbox-docker#1163]
### Current Behavior

I tried to install netbox, `docker compose up -d` and get this error
````
docker compose up -d
[+] Running 4/6
 ✔ Container netbox-docker-redis-1                Running                                                                                                                                                0.0s 
 ✔ Container netbox-docker-redis-cache-1          Running                                                                                                                                                0.0s 
 ✔ Container netbox-docker-postgres-1             Running                                                                                                                                                0.0s 
 ✘ Container netbox-docker-netbox-1               Error                                                                                                                                                  1.3s 
 ⠹ Container netbox-docker-netbox-housekeeping-1  Recreated                                                                                                                                              1.2s 
 ⠹ Container netbox-docker-netbox-worker-1        Recreated                                                                                                                                              1.2s 
dependency failed to start: container netbox-docker-netbox-1 exited (127)
```

### Expected Behavior

docker compose up -d
[+] Running 6/6
 ✔ Container netbox-docker-redis-1                Running                                                                                                                                                0.0s 
 ✔ Container netbox-docker-redis-cache-1          Running                                                                                                                                                0.0s 
 ✔ Container netbox-docker-postgres-1             Running                                                                                                                                                0.0s 
 ✔ Container netbox-docker-netbox-1               Running                                                                                                                                                1.3s 
 ✔ Container netbox-docker-netbox-housekeeping-1  Running                                                                                                                                                1.2s 
 ✔ Container netbox-docker-netbox-worker-1        Running                                                                                                                                                1.2s 
```

### Docker Compose Version

Docker Compose version v2.24.5

### Docker Version

```text
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```


### The git Revision

f1ca9ab7ebc16b288fd9da8825176c75d6b7ea4f

### The git Status

```text
Sur la branche release
Votre branche est à jour avec 'origin/release'.

rien à valider, la copie de travail est propre

On the release branch Your branch is up to date with 'origin/release'.

nothing to validate, the working copy is clean
```


### Startup Command

docker compose up -d

### NetBox Logs

```text
netbox-1  | /usr/bin/tini: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```


### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - "7000:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    environment:
      SKIP_SUPERUSER: "false"
      # SUPERUSER_API_TOKEN: ""
      # SUPERUSER_EMAIL: ""
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
```
