### ISSUE TITLE
Crash During API Call with ASP.NET Application Since Version 4.2.0

### ISSUE THREAD

**Issue by PapouMansot** [netbox-community/netbox-docker#1378]
### Current Behavior

Since updating to NetBox Docker version 4.2.0, API calls made from an ASP.NET application cause the NetBox service to crash. The logs indicate errors related to `nginx-unit` and messages about "core dumps".

Here are the relevant log excerpts:

⚙️ Applying configuration from /etc/unit/nginx-unit.json ✅ Unit configuration loaded successfully

2025/01/19 00:39:19 [notice] 7#7 process 100 exited with code 0

2025/01/19 00:41:26 [alert] 7#7 process 104 exited on signal 11 (core dumped)

2025/01/19 00:41:26 [alert] 7#7 sendmsg(10, -1, -1, 1) failed (32: Broken pipe)

🧬 loaded config '/etc/netbox/config/configuration.py' 🧬 loaded config '/etc/netbox/config/extra.py' 🧬 loaded config '/etc/netbox/config/logging.py' 🧬 loaded config '/etc/netbox/config/plugins.py'

2025/01/19 00:41:26 [info] 139#139 router started 2025/01/19 00:41:26 [info] 139#139 OpenSSL 3.0.13 30 Jan 2024, 300000d0 2025/01/19 00:41:26 [info] 140#140 "netbox" prototype started 2025/01/19 00:41:26 [info] 141#141 "netbox" application started 2025/01/19 00:41:26 [notice] 105#105 app process 106 exited with code 0 2025/01/19 00:41:26 [notice] 7#7 process 105 exited with code 0

...

2025/01/19 00:41:27 [alert] 7#7 process 139 exited on signal 11 (core dumped) 2025/01/19 00:41:27 [alert] 7#7 sendmsg(11, -1, -1, 1) failed (32: Broken pipe) 2025/01/19 00:41:27 [alert] 103#103 failed to apply previous configuration

After researching, it appears that the ASP.NET application adds a `traceparent` header to API requests, which may be causing the crash. For example:

192.168.1.37 - - [19/Jan/2025:00:24:58 +0000] "GET /api/virtualization/virtual-machines/?limit=200 HTTP/1.1" 200 585037 "-" "-" traceparent="00-37e835c8591e69c83762e375f1f690f1-827e37515eaa3024-00"

API calls work correctly when the `traceparent` header is not included.

### Expected Behavior

When an ASP.NET application makes an API call to NetBox, even if it includes the `traceparent` header, the NetBox service should process the request without crashing.

### Docker Compose Version

Docker Compose version v2.32.4

### Docker Version

```text
Client: Docker Engine - Community
 Version:           27.5.0
 API version:       1.47
 Go version:        go1.22.10
 Git commit:        a187fa5
 Built:             Mon Jan 13 15:25:08 2025
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          27.5.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       38b84dc
  Built:            Mon Jan 13 15:25:08 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

NetBox Community v4.2.2

### The git Status

```text
netbox_1  | ⚙️ Applying database migrations
netbox_1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/a.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
...
```

### Startup Command

With portainer

### NetBox Logs

```text
2025/01/19 00:41:27 [alert] 7#7 process 139 exited on signal 11 (core dumped) 2025/01/19 00:41:27 [alert] 7#7 sendmsg(11, -1, -1, 1) failed (32: Broken pipe) 2025/01/19 00:41:27 [alert] 103#103 failed to apply previous configuration
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    image: docker.io/netboxcommunity/netbox:latest
    restart: always
    user: 'root:root'  
    cap_add:
      - SETUID
      - SETGID
      - SETPCAP
    security_opt:
      - no-new-privileges:false
    ports:
      - "8080:8080"
    networks:
      - shared_network
    env_file:
      - stack.env
    depends_on:
      - postgres
      - redis
      - redis-cache

    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s

    volumes:
      - /opt/netbox-docker/configuration/logging.py:/etc/netbox/config/logging.py:z,ro
      - /opt/netbox-docker/test.log:/var/log/test.log:z,rw
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
      - netbox-static-files:/opt/netbox/netbox/static:rw

  netbox-worker:
    restart: always
    image: docker.io/netboxcommunity/netbox:latest
    user: 'unit:root'  
    env_file:
      - stack.env
    depends_on:
      - netbox
    networks:
      - shared_network
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker

  netbox-housekeeping:
    image: docker.io/netboxcommunity/netbox:latest
    restart: always
    user: 'unit:root'  
    env_file:
      - stack.env
    networks:
      - shared_network
    depends_on:
      - netbox
    command:
      - /opt/netbox/housekeeping.sh

  postgres:
    restart: always
    image: postgres:14-alpine  # Downgrade to a more stable version
    networks:
      - shared_network
    env_file:
      - stack.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 5

  # redis
  redis:
    image: docker.io/valkey/valkey:8.0-alpine
    networks:
      - shared_network
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: &redis-healthcheck
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    env_file: 
      - stack.env
    volumes:
      - netbox-redis-data:/data

  redis-cache:
    image: docker.io/valkey/valkey:8.0-alpine
    networks:
      - shared_network
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck: *redis-healthcheck
    env_file: 
      - stack.env
    volumes:
      - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local
  netbox-static-files:
    driver: local

networks:
  shared_network:
    external: true
```
