### ISSUE TITLE
Intermittent bad gateway response behind traefik

### ISSUE THREAD

**Issue by clarg18** [netbox-community/netbox-docker#1381]
### Current Behavior

When accessing the webpage from a browser, around 50% of requests return a 502/bad gateway error.

I am using netbox behind a traefik reverse proxy

```yaml
    networks:
      - netbox
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.netbox.entrypoints: "web, websecure"
      traefik.http.routers.netbox.rule: "Host(`ipam-docker-test.domain.com`)"
      traefik.http.routers.netbox.tls: "true"
      traefik.http.routers.netbox.service: "netbox"
      traefik.http.services.netbox.loadbalancer.server.port: "8080"  
```

When the 502 happens, I see nothing in the netbox logs. and when it works I obviously see the request.

Traefik also has no errors relating to this.

I am really unsure how to even start diagnosing it.

### Expected Behavior

Page loads every time

### Docker Compose Version

Docker Compose version v2.29.7

### Docker Version

```text
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.23
  GitCommit:        57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

bd9bdd063570915312bafdb8c4a6b120805deaa5

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   configuration/configuration.py
        modified:   configuration/ldap/extra.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        volumes/
```

### Startup Command

portainer stack

### NetBox Logs

```text
2025/01/20 11:36:23 [notice] 7#7 process 106 exited with code 0
2025/01/20 11:36:23 [info] 108#108 router started
2025/01/20 11:36:23 [info] 108#108 OpenSSL 3.0.13 30 Jan 2024, 300000d0
⚙️ Applying configuration from /etc/unit/nginx-unit.json
2025/01/20 11:36:24 [info] 111#111 "netbox" prototype started
2025/01/20 11:36:24 [info] 112#112 "netbox" application started
✅ Unit configuration loaded successfully
2025/01/20 11:36:26 [notice] 7#7 process 104 exited with code 0
2025/01/20 11:36:27 [info] 146#146 "netbox" application started
127.0.0.1 - - [20/Jan/2025:11:36:34 +0000] "GET /login/ HTTP/1.1" 200 3270 "-" "curl/8.5.0"
127.0.0.1 - - [20/Jan/2025:11:36:35 +0000] "GET /login/ HTTP/1.1" 200 3270 "-" "curl/8.5.0"
127.0.0.1 - - [20/Jan/2025:11:36:57 +0000] "GET /login/ HTTP/1.1" 200 3270 "-" "curl/8.5.0"
127.0.0.1 - - [20/Jan/2025:11:37:08 +0000] "GET /login/ HTTP/1.1" 200 3270 "-" "curl/8.5.0"
10.192.0.90 - - [20/Jan/2025:11:37:14 +0000] "GET / HTTP/1.1" 500 1611 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
10.192.0.90 - - [20/Jan/2025:11:37:15 +0000] "GET / HTTP/1.1" 500 1611 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
```

### Content of docker-compose.override.yml

```yaml
I'm using portainer:

services:
  netbox: &netbox
    image: docker.io/netboxcommunity/netbox:${VERSION-v4.2-3.1.0}
    depends_on:
      - postgres
      - redis
      - redis-cache
    expose:
      - 8080
    user: "unit:root"
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldaps://domain.com:636"
      AUTH_LDAP_BIND_DN: "CN=netbox_ldap,OU=Service Accounts,DC=domain,DC=com"
      AUTH_LDAP_BIND_PASSWORD: ""
      AUTH_LDAP_USER_SEARCH_BASEDN: "DC=domain,DC=com"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=Security Groups,DC=domain,DC=com"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=netbox_users,OU=Security Groups,DC=domain,DC=com"
      AUTH_LDAP_GROUP_TYPE: "NestedGroupOfNamesType"
      AUTH_LDAP_IS_ADMIN_DN: "cn=netbox_staff,ou=Security Groups,dc=domain,dc=com"
      AUTH_LDAP_IS_SUPERUSER_DN: "cn=netbox_admin,ou=Security Groups,dc=domain,dc=com"
      LDAP_IGNORE_CERT_ERRORS: "false"
      AUTH_LDAP_USER_ATTR_MAP: '{"username": "sAMAccountName", "first_name": "givenName", "last_name": "sn", "email": "mail"}'
      AUTH_LDAP_MIRROR_GROUPS: "True"
      AUTH_LDAP_FIND_GROUP_PERMS: "True"
      AUTH_LDAP_CONNECTION_OPTIONS: '{"OPT_REFERRALS": 0}'
      LDAP_CA_CERT_FILE: "/etc/ssl/certs/star.domain.fullchain.pem"

      CORS_ORIGIN_ALLOW_ALL: "True"
      DB_HOST: "postgres"
      DB_NAME: "netbox"
      DB_PASSWORD: ""
      DB_USER: "netbox"
      EMAIL_FROM: "netbox@bar.com"
      EMAIL_PASSWORD: ""
      EMAIL_PORT: "25"
      EMAIL_SERVER: "localhost"
      EMAIL_SSL_CERTFILE: ""
      EMAIL_SSL_KEYFILE: ""
      EMAIL_TIMEOUT: "5"
      EMAIL_USERNAME: "netbox"
      EMAIL_USE_SSL: "false"
      EMAIL_USE_TLS: "false"
      GRAPHQL_ENABLED: "true"
      HOUSEKEEPING_INTERVAL: "86400"
      MEDIA_ROOT: "/opt/netbox/netbox/media"
      METRICS_ENABLED: "false"
      REDIS_CACHE_DATABASE: "1"
      REDIS_CACHE_HOST: "redis-cache"
      REDIS_CACHE_INSECURE_SKIP_TLS_VERIFY: "false"
      REDIS_CACHE_PASSWORD: ""
      REDIS_CACHE_SSL: "false"
      REDIS_DATABASE: "0"
      REDIS_HOST: "redis"
      REDIS_INSECURE_SKIP_TLS_VERIFY: "false"
      REDIS_PASSWORD: ""
      REDIS_SSL: "false"
      RELEASE_CHECK_URL: "https://api.github.com/repos/netbox-community/netbox/releases"
      SECRET_KEY: "''"
      SKIP_SUPERUSER: "true"
      WEBHOOKS_ENABLED: "true"
    volumes:
      - /opt/docker/netbox/configuration:/etc/netbox/config:z,ro
      - /opt/docker/netbox/volumes/netbox/media:/opt/netbox/netbox/media:rw
      - /opt/docker/netbox/volumes/netbox/reports-files:/opt/netbox/netbox/reports:rw
      - /opt/docker/netbox/volumes/netbox/scripts-files:/opt/netbox/netbox/scripts:rw
      - /opt/docker/netbox/certs/star.domain.com.fullchain.pem:/etc/ssl/certs/star.domain.fullchain.pem:ro
    networks:
      - netbox
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.netbox.entrypoints: "web, websecure"
      traefik.http.routers.netbox.rule: "Host(`ipam-docker-test.domain.com`)"
      traefik.http.routers.netbox.tls: "true"
      traefik.http.routers.netbox.service: "netbox"
      traefik.http.services.netbox.loadbalancer.server.port: "8080"  
  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    labels: 
      traefik.enable: "false"
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
  netbox-housekeeping:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/housekeeping.sh
    healthcheck:
      test: ps -aux | grep -v grep | grep -q housekeeping || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s

  # postgres
  postgres:
    image: docker.io/postgres:17-alpine
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    environment:
      POSTGRES_DB: "netbox"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "netbox"
    volumes:
      - /opt/docker/netbox/volumes/postgresql/data:/var/lib/postgresql/data
    networks:
      - netbox

  # redis
  redis:
    image: docker.io/valkey/valkey:8.0-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    environment:
      REDIS_PASSWORD: ""
    healthcheck: &redis-healthcheck
      test: '[ $$(valkey-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    volumes:
      - /opt/docker/netbox/volumes/redis/data:/data
    networks:
      - netbox
  redis-cache:
    image: docker.io/valkey/valkey:8.0-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - valkey-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    environment:
      REDIS_PASSWORD: ""
    healthcheck: *redis-healthcheck
    volumes:
      - /opt/docker/netbox/volumes/redis/cache:/data
    networks:
      - netbox


networks:
  netbox:
    name: netbox
  traefik:
    external: true
```
