### ISSUE TITLE
Instructions missing required env variables.

### ISSUE THREAD

**Issue by celeroncool** [netbox-community/netbox-docker#1430]
### Desired Behavior

Hello, If I now setup netbox-docker from git repo and follow instructions to use my own env file, the docker-compose.override.yml file is missing instuctions to use your own env file.

### Contrast to Current Behavior

I would like to have more examples for beginners in the override example file, so that its easier to understand.

### Required Changes

For example, if you use own env files, you need to also add them to housekeeping and worker:
docker-compose.override.example.yml
```
services:
  netbox:
    ports:
      - "8000:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    # If you want to automatically start containers after reboot, add restart: unless-stopped to all units.
    restart: unless-stopped 
    env_file: env/dev-netbox.env
  netbox-worker:
    restart: unless-stopped
    # If you use your own env file, make sure to add it to netbox-worker and netbox-housekeeping
    env_file: env/dev-netbox.env
  netbox-housekeeping:
    restart: unless-stopped
    # If you use your own env file, make sure to add it to netbox-worker and netbox-housekeeping
    env_file: env/dev-netbox.env
  postgres:
    restart: unless-stopped
    env_file: env/dev-postgres.env
  redis:
    restart: unless-stopped
    env_file: env/dev-redis.env
  redis-cache:
    restart: unless-stopped
    env_file: env/dev-redis-cache.env
```
