### ISSUE TITLE
configuration.py not present

### ISSUE THREAD

**Issue by onenetworkguy** [netbox-community/netbox-docker#237]
## Current Behavior

When attempting to bring up the netbox container both `netbox_1` and `netbox-worker_1` fail to start and exit.
...

## Expected Behavior

Expect containers to not fail to start.
...

## Debug Information

The output of `docker-compose version`:
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```
The output of `docker version`:
```
lient: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
The output of `git rev-parse HEAD`: Downloaded `release` branch from github as `.zip`

The command you used to start the project:
```
docker-compose pull
docker-compose up -d
```

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{
   "NETBOX_GIT_BRANCH":"HEAD",
   "NETBOX_GIT_REF":"295d4f0394b431351c0cb2c3ecc791df68c6c2fb",
   "NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git",
   "ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:v2.7.1",
   "org.label-schema.build-date":"2020-01-23T08:55+00:00",
   "org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.label-schema.name":"Netbox Docker",
   "org.label-schema.schema-version":"1.0",
   "org.label-schema.url":"https://github.com/netbox-community/netbox-docker",
   "org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.label-schema.vcs-ref":"d058b7bc934c80876bc3fdf9e13bcb830622a4db",
   "org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git",
   "org.label-schema.vendor":"The netbox-docker contributors.",
   "org.label-schema.version":"0.21.0",
   "org.opencontainers.image.authors":"The netbox-docker contributors.",
   "org.opencontainers.image.created":"2020-01-23T08:55+00:00",
   "org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.",
   "org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki",
   "org.opencontainers.image.licenses":"Apache-2.0",
   "org.opencontainers.image.revision":"d058b7bc934c80876bc3fdf9e13bcb830622a4db",
   "org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git",
   "org.opencontainers.image.title":"Netbox Docker",
   "org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker",
   "org.opencontainers.image.vendor":"The netbox-docker contributors.",
   "org.opencontainers.image.version":"0.21.0"
}
```

The output of `docker-compose logs netbox`:

```text
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/netbox/netbox/configuration.py", line 7, in <module>
netbox_1         |     spec.loader.exec_module(module)
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 859, in get_code
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 916, in get_data
netbox_1         | FileNotFoundError: [Errno 2] No such file or directory: '/etc/netbox/config/configuration.py'
netbox_1         |
netbox_1         | During handling of the above exception, another exception occurred:
netbox_1         |
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 42, in <module>
netbox_1         |     from netbox import configuration
netbox_1         |   File "/opt/netbox/netbox/netbox/configuration.py", line 10, in <module>
netbox_1         |     raise ImportError('')
netbox_1         | ImportError
netbox_1         |
netbox_1         | During handling of the above exception, another exception occurred:
netbox_1         |
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
netbox_1         |     self.check()
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
netbox_1         |     include_deployment_checks=include_deployment_checks,
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
netbox_1         |     issues = run_checks(tags=[Tags.database])
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
netbox_1         |     new_errors = check(app_configs=app_configs)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
netbox_1         |     for conn in connections.all():
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 216, in all
netbox_1         |     return [self[alias] for alias in self]
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
netbox_1         |     return iter(self.databases)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
netbox_1         |     res = instance.__dict__[self.name] = self.func(instance)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
netbox_1         |     self._databases = settings.DATABASES
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
netbox_1         |     self._setup(name)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
netbox_1         |     self._wrapped = Settings(settings_module)
netbox_1         |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
netbox_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1         |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
netbox_1         |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1         |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
netbox_1         |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
netbox_1         |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 45, in <module>
netbox_1         |     "Configuration file is not present. Please define netbox/netbox/configuration.py per the documentation."
netbox_1         | django.core.exceptions.ImproperlyConfigured: Configuration file is not present. Please define netbox/netbox/configuration.py per the documentation.
netbox_1         | ❌ Waited 30s or more for the DB to become ready.
```

The output of `docker-compose logs nginx`:

```text
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: using the "epoll" event method
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: nginx/1.17.8
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: built by gcc 8.3.0 (Alpine 8.3.0)
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: OS: Linux 4.9.125-linuxkit
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: start worker processes
nginx_1          | 2020/02/04 20:36:50 [notice] 1#1: start worker process 6
nginx_1          | 2020/02/04 20:39:58 [notice] 1#1: signal 15 (SIGTERM) received, exiting
nginx_1          | 2020/02/04 20:39:58 [notice] 6#6: exiting
nginx_1          | 2020/02/04 20:39:58 [notice] 6#6: exit
nginx_1          | 2020/02/04 20:39:58 [notice] 1#1: signal 14 (SIGALRM) received
nginx_1          | 2020/02/04 20:39:58 [notice] 1#1: signal 17 (SIGCHLD) received from 6
nginx_1          | 2020/02/04 20:39:58 [notice] 1#1: worker process 6 exited with code 0
nginx_1          | 2020/02/04 20:39:58 [notice] 1#1: exit
```

**Comment by cimnine** [comment]
Could you also post the `docker-compose.yml` (and `docker-compose.override.yml` if you have it)?

**Comment by onenetworkguy** [comment]
`docker-compose.yml`

```
version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:${VERSION-latest}
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-nginx-config:/etc/netbox-nginx:z
    - netbox-static-files:/opt/netbox/netbox/static:z
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.17-alpine
    depends_on:
    - netbox
    ports:
    - 8080
    volumes:
    - netbox-static-files:/opt/netbox/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:11-alpine
    env_file: env/postgres.env
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:5-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
```

Don't have `docker-compose.override.yml`
