### ISSUE TITLE
Add ARM Version

### ISSUE THREAD

**Issue by maximegy** [netbox-community/netbox-docker#306]
Hello,
There's no ARM version of the netbox docker image.

I've tried to full build on my Raspberry PI and it don't work.
I've tried infinytum/netbox at https://hub.docker.com/r/infinytum/netbox but it don't work, i have these errors : 
- `Unknown command: 'rqworker'` on the worker
- `ModuleNotFoundError: No module named 'utilities.choices'` on the netbox image
- ' `2020/05/30 12:17:14 [error] 6#6: *15 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.16.254.69, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.24.0.6:8001/favicon.ico", host: "172.16.254.13:8080", referrer: "http://172.16.254.13:8080/"` ' on the nginx container.

There is my docker-compose file : 
```
version: '3.4'
services:
  netbox: &netbox
    image: infinytum/netbox:latest
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-nginx-config:/etc/netbox-nginx:z
    - netbox-static-files:/opt/netbox/netbox/static:z
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.17-alpine
    depends_on:
    - netbox
    ports:
    - 8080:8080
    volumes:
    - netbox-static-files:/opt/netbox/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:11-alpine
    env_file: env/postgres.env
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:5-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis-cache.env
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
```

Can you provide a ARM OS/ARCH on the latest tag ?
Thanks
