### ISSUE TITLE
Dynamic Variables

### ISSUE THREAD

**Issue by cimnine** [netbox-community/netbox-docker#318]
## Desired Behavior

Plugins (#317), but also other configuration items (e.g. remote storage #311 and remote auth #310), require more flexibility than just the basic value types string, boolean or number.

IMO it would be great if there was a directory where every file placed in it would be loaded and merged with the current configuration. The pattern is well-known in the Debian/Ubuntu world, where there's often a `config.d` directory, for example cron's `/etc/cron.d`.

Plugins could place their configuration in there. And other configuration files for remote storage and remote auth could be placed in there as well. They would all be loaded during the startup of Netbox.

Example:

```py
# /etc/netbox/config.d/configuration.PLUGIN.py

PLUGINS += 'plugin_name'
PLUGINS_CONFIG['plugin_name'] = {
  'foo': 'bar',
  'buzz': 'bazz',
}
```

## Contrast to Current Behavior

Currently we only have variables that are strings, numbers or booleans.

### Suggestion in #310 and #311

This suggestion uses eval, which I don't like. I fear that it will be misused by containing Python code, rather than just `dict`s, and that it will not return nice error messages leading to issues on Github and questions in the chat that could be preventable.

```py
ast.literal_eval(os.environ.get('STORAGE_CONFIG', "{}"))
```

### Suggestion in #317

This suggestion uses comma separated lists and json.

```py
PLUGINS = list(filter(lambda x: x != '', os.environ.get('PLUGINS', '').split(',')))
PLUGINS_CONFIG = json.loads(os.environ.get('PLUGINS_CONFIG', '{}'))
```

I don't like JSON in ENV variables. The comma-separated solution isn't ideal either, as it will require the user's interaction. (I.e. it's not possible to _add the plugin to the Dockerfile and it just works_ (apart from mandatory configuration).

## Changes Required

Probably [docker/configuration.docker.py](https://github.com/netbox-community/netbox-docker/blob/b46bd58e0a809e083a5d1165d2c368c442a2cc73/docker/configuration.docker.py) and maybe [configuration/configuration.py](https://github.com/netbox-community/netbox-docker/blob/1f38ca0a8642fa85013d5ecce30de2fb201c9180/configuration/configuration.py).

## Discussion: Benefits and Drawbacks

[What I've written in #310](https://github.com/netbox-community/netbox-docker/pull/310#issuecomment-657532858):

> From a first glance, what I don't like are the literal_eval statements which you make use of. My opinion is that if a configuration property is too complex to be a simple type (string, bool, number), then it should be loaded from a file. Because a file can be type-checked, formatted, commented, etc. Docker has perfect support for mounting (config) files, so I would prefer if REMOTE_AUTH_DEFAULT_PERMISSIONS was actually REMOTE_AUTH_DEFAULT_PERMISSION_CONFIG and the value a path to the respective file (Python, YAML, JSON, ...).
> 
> Since this is a problem in other open PRs as well, maybe – instead of loading X additional files (or eval X env variables for that matter) – we should aim for a more flexible option altogether, e.g. loading all files in a certain directory (e.g. /etc/netbox/config/*) and evaluate them in the context of the config file (i.e. changing the way configuration.docker.py works).

[And in #311](https://github.com/netbox-community/netbox-docker/pull/311#issuecomment-657555811), regarding a solution proposed there:

> But I think it is still not good, because one would be forced to store secrets in environment variables – something that should be avoided in any production environment – without providing an option not to do so.

This last piece makes it evident to me, that the only solution for dynamic configuration values would be files, as such dynamic content may involve secrets.

I would love to hear feedback on this.

**Comment by shuichiro-makigaki** [comment]
The configuration directory is a good idea, especially for the plugin feature. Plugins can evolve alongside Netbox, which is a significant advantage. Instead, plugin users should add plugins and fix the configuration by themselves.  For the implementation, [Django Wiki](https://code.djangoproject.com/wiki/SplitSettings) shows some actual examples for merging multiple configuration files.

Regarding dynamic variables in remote authorization configs or storage backend configs, of course, they can be defined under `conf.d/`, but also should be configured via environment variables. This is because these features are in the core of Netbox and should be used out-of-box or by the minimum effort (e.g. changing env vars). In this case, [Django-environ](https://django-environ.readthedocs.io/en/latest/) seems to be helpful because it supports typecasting.

**Comment by gervaso** [comment]
I also agree on this approach, but I would also encourage to maintain a full k8s compatibility.
How could this be achieved?

I used [this helm chart](https://hub.helm.sh/charts/enix/netbox) to deploy netbox to k8s (this is what actually led to #311 ) and I don't think there's a way to push config files. (and it would be the same with plain ks8 deployments)

**Comment by ylmrx** [comment]
I also agree on limiting the env_vars configurability if this isn't something we want to push further. :+1:

**Comment by ylmrx** [comment]
`I also agree on this approach, but I would also encourage to maintain a full k8s compatibility.`

I'm facing the same issue here, will try to mount a configmap on that regard this week, we can stay in touch if you need help on this topic.

**Comment by gervaso** [comment]
Hi @ylmrx I think the mounted configmap approach you're suggesting could be the correct solution to this problem.
To work with k8s it would require modifications to:

- This project, to load config snippets from the /etc/netbox.conf.d directory, as already suggested by the maintainer
- The helm charts, which should provide some sort of "extraConfigMap" value

I'll try to recap them here:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-configuration-plugins
data:
  configuration.PLUGIN.py: |
    PLUGINS += 'plugin_name'
    PLUGINS_CONFIG['plugin_name'] = {
      'foo': 'bar',
      'buzz': 'bazz',
    }
```

And something this in the pod definition:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: netbox-pod
spec:
  containers:
    - name: netbox
      image: netbox/netbox
      volumeMounts:
      - name: plugin-config
        mountPath: "/etc/netbox/config.d"
        readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: plugin-config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: netbox-configuration-plugins
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "configuration.PLUGIN.py"
          path: "configuration.PLUGIN.py"
```

Of course this approach supports multiple items to expose as plugins. The only downside I see is on the "validation" of the python config snippets inside each item (it would be quite easy to mistype something or break the indentation, and well, inject malicious code but I think that's out of scope here).

Is this what you were thinking of?
