### ISSUE TITLE
3.2.7 fails with netbox-worker_1 raising exception that it can't start new thread

### ISSUE THREAD

**Issue by alanNutanix** [netbox-community/netbox-docker#814]
### Current Behavior

docker-compose up and the netbox-worker_1 fails to come up which causes the netbox_1 to also come up.

### Expected Behavior

I expected that it would work like it did in previous versions.

3.2.5-ldap  - works great
3.2.6 - comes up, ldap doesn't work (known issue - #799) 
3.2.7 - doesn't come up

### Docker Compose Version

docker-compose version 1.23.1, build b02f1306 docker-py version: 3.5.0 CPython version: 3.6.7 OpenSSL version: OpenSSL 1.1.0f  25 May 2017

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.39
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:15 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   configuration/logging.py
	modified:   configuration/plugins.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	plugins

no changes added to commit (use "git add" and/or "git commit -a")
```

### Startup Command

docker-compose down && docker-compose up &

### NetBox Logs

```text
(since problem is with worker, here is the logs from all the containers)
Attaching to netbox-docker-dev_netbox_1_6fc3c5f81d13, netbox-docker-dev_netbox-housekeeping_1_fae7aacd511c, netbox-docker-dev_netbox-worker_1_d2cb2a481462, netbox-docker-dev_redis-cache_1_48e41af4f510, netbox-docker-dev_redis_1_1c314351c5ff, netbox-docker-dev_postgres_1_5ec35b05ed51
redis-cache_1_48e41af4f510 | 1:C 27 Jul 2022 17:47:32.525 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-cache_1_48e41af4f510 | 1:C 27 Jul 2022 17:47:32.525 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-cache_1_48e41af4f510 | 1:C 27 Jul 2022 17:47:32.525 # Configuration loaded
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.526 * monotonic clock: POSIX clock_gettime
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.527 * Running mode=standalone, port=6379.
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.527 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.527 # Server initialized
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.527 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-cache_1_48e41af4f510 | 1:M 27 Jul 2022 17:47:32.527 * Ready to accept connections
netbox-housekeeping_1_fae7aacd511c | Interval set to 86400 seconds
netbox-housekeeping_1_fae7aacd511c | Wed Jul 27 17:47:34 UTC 2022
netbox-housekeeping_1_fae7aacd511c | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-housekeeping_1_fae7aacd511c | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-housekeeping_1_fae7aacd511c | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-housekeeping_1_fae7aacd511c | 🧬 loaded config '/etc/netbox/config/nutanix_extra_config.py'
netbox-housekeeping_1_fae7aacd511c | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-housekeeping_1_fae7aacd511c | [*] Clearing expired authentication sessions
netbox-housekeeping_1_fae7aacd511c | 	Sessions cleared.
netbox-housekeeping_1_fae7aacd511c | [*] Checking for expired changelog records
netbox-housekeeping_1_fae7aacd511c | 	No expired records found.
netbox-housekeeping_1_fae7aacd511c | [*] Checking for expired jobresult records
netbox-housekeeping_1_fae7aacd511c | 	No expired records found.
netbox-housekeeping_1_fae7aacd511c | [*] Checking for latest release
netbox-housekeeping_1_fae7aacd511c | 	Latest release: 3.2.7
netbox-housekeeping_1_fae7aacd511c | Finished.
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/nutanix_extra_config.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1_6fc3c5f81d13  | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox_1_6fc3c5f81d13  | ↩️ Skipping startup scripts
netbox_1_6fc3c5f81d13  | ✅ Initialisation is done.
netbox_1_6fc3c5f81d13  | ⏳ Waiting for control socket to be created... (1/10)
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [warn] 7#7 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [info] 7#7 unit 1.27.0 started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [info] 14#14 discovery started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [notice] 14#14 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [info] 7#7 controller started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [notice] 7#7 process 14 exited with code 0
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [info] 16#16 router started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:51 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
netbox_1_6fc3c5f81d13  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:52 [info] 20#20 "netbox" prototype started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:52 [info] 21#21 "netbox" application started
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [alert] 16#16 pthread_create() failed (1: Operation not permitted)
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [alert] 16#16 failed to apply new conf
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/nutanix_extra_config.py'
netbox_1_6fc3c5f81d13  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1_6fc3c5f81d13  | ⚠️ Could no load Unit configuration
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [alert] 7#7 sendmsg(10, -1, -1, 1) failed (32: Broken pipe)
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [notice] 7#7 process 15 exited with code 0
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [notice] 7#7 process 12 exited with code 1
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:54 [notice] 7#7 process 16 exited with code 0
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:55 [notice] 20#20 app process (isolated 21) exited with code 0
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:55 [alert] 20#20 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
netbox_1_6fc3c5f81d13  | 2022/07/27 17:47:55 [notice] 7#7 process 20 exited with code 0
redis_1_1c314351c5ff   | 1:C 27 Jul 2022 17:47:33.514 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_1c314351c5ff   | 1:C 27 Jul 2022 17:47:33.514 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_1c314351c5ff   | 1:C 27 Jul 2022 17:47:33.514 # Configuration loaded
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.514 * monotonic clock: POSIX clock_gettime
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.515 * Running mode=standalone, port=6379.
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.515 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.515 # Server initialized
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * Reading RDB base file on AOF loading...
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * Loading RDB produced by version 7.0.3
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * RDB age 97067 seconds
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * RDB memory usage when created 0.82 Mb
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * RDB is base AOF
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.516 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.517 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.001 seconds
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.518 * DB loaded from append only file: 0.002 seconds
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.518 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
redis_1_1c314351c5ff   | 1:M 27 Jul 2022 17:47:33.518 * Ready to accept connections
netbox-worker_1_d2cb2a481462 | No queues have been specified. This process will service the following queues by default: high, default, low
netbox-worker_1_d2cb2a481462 | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-worker_1_d2cb2a481462 | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-worker_1_d2cb2a481462 | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-worker_1_d2cb2a481462 | 🧬 loaded config '/etc/netbox/config/nutanix_extra_config.py'
netbox-worker_1_d2cb2a481462 | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-worker_1_d2cb2a481462 | Traceback (most recent call last):
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/netbox/manage.py", line 10, in <module>
netbox-worker_1_d2cb2a481462 |     execute_from_command_line(sys.argv)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-worker_1_d2cb2a481462 |     utility.execute()
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
netbox-worker_1_d2cb2a481462 |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
netbox-worker_1_d2cb2a481462 |     self.execute(*args, **cmd_options)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
netbox-worker_1_d2cb2a481462 |     output = self.handle(*args, **options)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/netbox/extras/management/commands/rqworker.py", line 26, in handle
netbox-worker_1_d2cb2a481462 |     super().handle(*args, **options)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/django_rq/management/commands/rqworker.py", line 130, in handle
netbox-worker_1_d2cb2a481462 |     w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/rq/worker.py", line 563, in work
netbox-worker_1_d2cb2a481462 |     self.subscribe()
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/rq/worker.py", line 535, in subscribe
netbox-worker_1_d2cb2a481462 |     self.pubsub_thread = self.pubsub.run_in_thread(sleep_time=0.2, daemon=True)
netbox-worker_1_d2cb2a481462 |   File "/opt/netbox/venv/lib/python3.10/site-packages/redis/client.py", line 1736, in run_in_thread
netbox-worker_1_d2cb2a481462 |     thread.start()
netbox-worker_1_d2cb2a481462 |   File "/usr/lib/python3.10/threading.py", line 928, in start
netbox-worker_1_d2cb2a481462 |     _start_new_thread(self._bootstrap, ())
netbox-worker_1_d2cb2a481462 | RuntimeError: can't start new thread
postgres_1_5ec35b05ed51 |
postgres_1_5ec35b05ed51 | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1_5ec35b05ed51 |
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.574 UTC [1] LOG:  starting PostgreSQL 13.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.575 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.575 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.579 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.585 UTC [21] LOG:  database system was shut down at 2022-07-27 17:47:30 UTC
postgres_1_5ec35b05ed51 | 2022-07-27 17:47:32.590 UTC [1] LOG:  database system is ready to accept connections
```

### Content of docker-compose.override.yml

```yaml
version: "3.4"
services:
    postgres:
      image: postgres:13-alpine
      environment:
        POSTGRES_PASSWORD: "TrulySecretPassword"
    redis-cache:
      environment:
        REDIS_PASSWORD: "TrulySecretPassword"
    redis:
      environment:
        REDIS_PASSWORD: "TrulySecretPassword"

    netbox: &netbox
      image: netboxcommunity/netbox:v3.2.7
      volumes:
        - ./plugins:/opt/netbox/plugins:z,ro
      environment:
        # SKIP_SUPERUSER: "true"

        SECRET_KEY: "TrulySecretKey"
        DB_PASSWORD:       "TrulySecretPassword"
        REDIS_PASSWORD:    "TrulySecretPassword"
        REDIS_CACHE_PASSWORD: "TrulySecretPassword"
        ALLOWED_HOSTS: "localhost ::1 127.0.0.1 netbox.example.com"
        SKIP_STARTUP_SCRIPTS: "true"
        EXEMPT_VIEW_PERMISSIONS: "*"
        # This does not allow service accounts which were allowed before
      ports:
        - 8080:8080
    netbox-worker:
      <<: *netbox
      ports: []
    netbox-housekeeping:
      <<: *netbox
      ports: []
```

**Comment by doc-sheet** [comment]
Could you try to update your docker at least to 20.10.10?
I believe you have the same issue with `clone3()` syscall
https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921

**Comment by Fyne5** [comment]
Yes, me too, and my docker-ce had been upgraded to newest version

```
[root@li2233-30 09:44:14 /srv/netbox-docker]# docker-compose version
Docker Compose version v2.8.0
```
```
[root@li2233-30 09:44:21 /srv/netbox-docker]# docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

My docker-compose.yaml (3.2.7 standard)
```
version: '3.4'
services:
  netbox: &netbox
    #image: netboxcommunity/netbox:${VERSION-v3.2-2.1.0}
    image: netboxcommunity/netbox:v3.2.7
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: env/netbox.env
    user: 'unit:root'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    - postgres
    command:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    - rqworker
  netbox-housekeeping:
    <<: *netbox
    depends_on:
    - redis
    - postgres
    command:
    - /opt/netbox/housekeeping.sh
```
![Screen Shot 2022-08-01 at 09 42 57](https://user-images.githubusercontent.com/58161454/182062599-9c31409c-0250-4fc1-b2af-2ce186f6fca5.JPEG)

**Comment by Fyne5** [comment]
Updated: after upgrade containerd and reboot the server, docker-compose with netbox 3.2.7 is up now
![Screen Shot 2022-08-02 at 11 23 43](https://user-images.githubusercontent.com/58161454/182291347-fd1a2f79-66dc-4a0f-9a2c-fa4fb6959729.JPEG)
.

**Comment by alanNutanix** [comment]
I finally got around to upgrading the version of docker.   That fixed the issue.

**Comment by duckw** [comment]
Unfortunately I am running on an old docker host which I can't upgrade at the moment.
The following modification to the docker-compose.override.yml worked for me.  Hope this helps someone else out.

```
version: "3.4"
services:
  netbox:
    security_opt:
      - seccomp:unconfined
  netbox-worker:
    image: *NetboxImage
    security_opt:
      - seccomp:unconfined
```
