### ISSUE TITLE
When LDAP is down, netbox does not allow to login via local super user

### ISSUE THREAD

**Issue by github-admin-lavego** [netbox-community/netbox-docker#823]
### Steps to reproduce:

1. Deploy netbox-docker using the docker-compose file provided here: [docker-compose.yml](https://github.com/netbox-community/netbox-docker/blob/release/docker-compose.override.yml.example)
2. Provide LDAP env variables in the docker-compose file to setup LDAP.
3. After netbox is up and running, block the connection between Netbox deployment and LDAP server using firewall.
4. Then try to login with the local super user mentioned here: [Super User](https://github.com/netbox-community/netbox-docker/blob/release/env/netbox.env#L39-L42)

### Expected Behavior

Netbox should allow local users to login even when connection to LDAP fails.

This is probably the issue: https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/api/authentication.py#L28-L38

There is only a check for presence of LDAP and then try to login via LDAP. There should be a fallback to validate local users in case of connections errors to LDAP. Maybe another if condition?

### Docker Compose Version

1.29.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

### The git Revision

ebda4660de9edc5731497e92a98395b4ec16e613

### The git Status

```text
On branch netbox-docker_2.1.0
nothing to commit, working tree clean
```

### Startup Command

docker-compose up

### NetBox Logs

```text
[06/Aug/2022:14:54:21 +0000] "GET /login/?next=/ HTTP/1.0" 200 8559 "https://netbox.domain/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36"
Caught LDAPError while authenticating <<super_user>>: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Transport endpoint is not connected'})
[06/Aug/2022:14:56:50 +0000] "POST /login/ HTTP/1.0" 302 0 "https://netbox.domain/login/?next=/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36"
```

### Content of docker-compose.override.yml

```yaml
---
version: '3.4'
services:
  netbox:
    image: netboxcommunity/netbox:v3.2.7-2.1.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
  
  netbox-worker:
    image: netboxcommunity/netbox:v3.2.7-2.1.0
    restart: unless-stopped
  
  netbox-housekeeping:
    image: netboxcommunity/netbox:v3.2.7-2.1.0
    restart: unless-stopped
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  
  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
```
