### ISSUE TITLE
Docker creating temporary random volume for Redis Cache on every Restart

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-docker#851]
### Current Behavior

In compose there is no persistant volume defined for Redis Cache. 
So Docker creates a random Volume on every Start from Netbox for Redis-Cache.
This volume wouldnt be delete automaticly.

Redis-Cache didnt write data to this volume so i Think we can add a static volume on defautl.

### Expected Behavior

Redis-Cache didnt write data to this volume so i Think we can add a static volume on default.

### Docker Compose Version

Docker Compose version v2.10.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:43 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:30 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

3f1e45f636f9ff0b81e61a3f779e39f1919fdf7d

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Dockerfile-Plugins
        plugin_requirements.txt

nothing added to commit but untracked files present (use "git add" to track)
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-docker-netbox-1  | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox-docker-netbox-1  | ⚠️⚠️⚠️ WARNING: The initializers have been moved to a plugin. See release notes.
netbox-docker-netbox-1  | ⚠️⚠️⚠️ Set environment variable 'SKIP_STARTUP_SCRIPTS' to 'true' to remove this warning.
netbox-docker-netbox-1  | ✅ Initialisation is done.
netbox-docker-netbox-1  | ⏳ Waiting for control socket to be created... (1/10)
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [warn] 8#8 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [info] 8#8 unit 1.27.0 started
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [info] 15#15 discovery started
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [notice] 15#15 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [info] 8#8 controller started
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [notice] 8#8 process 15 exited with code 0
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [info] 17#17 router started
netbox-docker-netbox-1  | 2022/09/23 12:06:24 [info] 17#17 OpenSSL 3.0.2 15 Mar 2022, 30000020
netbox-docker-netbox-1  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-docker-netbox-1  | 2022/09/23 12:06:25 [info] 21#21 "netbox" prototype started
netbox-docker-netbox-1  | 2022/09/23 12:06:25 [info] 22#22 "netbox" application started
netbox-docker-netbox-1  | ✅ Unit configuration loaded successfully
netbox-docker-netbox-1  | 2022/09/23 12:06:27 [notice] 8#8 process 13 exited with code 0
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    restart: always
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
  netbox-worker:
    restart: always 
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    restart: always 
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  postgres:
    restart: always
    
  redis:
    restart: always

  redis-cache:
    restart: always
```
