### ISSUE TITLE
Netbox exists after a couple of requests

### ISSUE THREAD

**Issue by telmich** [netbox-community/netbox-docker#854]
### Current Behavior

Netbox exits after a few requests, causing nginx-ingress to return a 404 on failure.
Note though, that the container keeps running, it's merely the python/django process exiting.

This restart happens sometimes after 8 requests, sometimes after 20ish requests, but rather frequent. As exit code 0 is a success code, I wonder what the motivation for netbox is to exit.

### Expected Behavior

Netbox does not exit on its own. By exiting the nginx-ingress will return a 404 to clients, every time netbox is unreachable.

### Docker Compose Version

kubernetes 1.24

### Docker Version

```text
crio / unrelated
```

### The git Revision

docker-hub versions: v3.3.2-2.2.0, v3.3.4-2.2.0

### The git Status

```text
No git
```

### Startup Command

The image directly, no commands

### NetBox Logs

```text
2a0a:e5c0:10:2:6c4c:27bd:c596:4da4 - - [28/Sep/2022:14:11:55 +0000] "GET /ipam/prefixes/39/prefixes/ HTTP/1.1" 200 108611 "https://netbox.xxx/ipam/prefixes/39/" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
2022/09/28 14:13:54 [notice] 20#20 app process (isolated 222) exited with code 0
```
```


### Content of docker-compose.override.yml

```yaml
- name: netbox
          image: netboxcommunity/netbox:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-netbox-secret
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-config
                  key: POSTGRES_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-config
                  key: POSTGRES_DB
```
```
