### ISSUE TITLE
REMOTE_AUTH_DEFAULT_PERMISSIONS

### ISSUE THREAD

**Issue by Sweepers007** [netbox-community/netbox-docker#890]
### Current Behavior

Hi, 
When assigning this permissions it does not do anything for the remote user(Social user).  Anyone below is ignored.  Tried in the env/netbox.env file and configuration.py.

REMOTE_AUTH_DEFAULT_PERMISSIONS = {'View_all': {}}
REMOTE_AUTH_DEFAULT_PERMISSIONS = {'View_all': None}
REMOTE_AUTH_DEFAULT_PERMISSIONS = {'dcim.view_device': None}

Also included
#REMOTE_AUTH_GROUP_SYNC_ENABLED = False

Any advice?

### Expected Behavior

We expecting the remote authed user to login and inherit the permission we define as defualt.  They get no permissions.

### Docker Compose Version

Docker Compose version v2.12.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

58a157983259d3a9992776dbe9f166ca11d2f987

### The git Status

```text
Main branch
```

### Startup Command

docker compose up

### NetBox Logs

```text
WARN[0000] The "v4" variable is not set. Defaulting to a blank string. 
WARN[0000] The "v4" variable is not set. Defaulting to a blank string. 
WARN[0000] The "v4" variable is not set. Defaulting to a blank string. 
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-docker-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-docker-netbox-1  | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox-docker-netbox-1  | ⚠️⚠️⚠️ WARNING: The initializers have been moved to a plugin. See release notes.
netbox-docker-netbox-1  | ⚠️⚠️⚠️ Set environment variable 'SKIP_STARTUP_SCRIPTS' to 'true' to remove this warning.
netbox-docker-netbox-1  | ✅ Initialisation is done.
netbox-docker-netbox-1  | ⏳ Waiting for control socket to be created... (1/10)
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [info] 7#7 unit 1.27.0 started
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [info] 17#17 discovery started
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [notice] 17#17 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [info] 7#7 controller started
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [info] 19#19 router started
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [notice] 7#7 process 17 exited with code 0
netbox-docker-netbox-1  | 2022/11/24 15:26:22 [info] 19#19 OpenSSL 3.0.2 15 Mar 2022, 30000020
netbox-docker-netbox-1  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-docker-netbox-1  | 2022/11/24 15:26:23 [info] 23#23 "netbox" prototype started
netbox-docker-netbox-1  | 2022/11/24 15:26:23 [info] 24#24 "netbox" application started
netbox-docker-netbox-1  | ✅ Unit configuration loaded successfully
netbox-docker-netbox-1  | 2022/11/24 15:26:24 [notice] 7#7 process 15 exited with code 0
netbox-docker-netbox-1  | 2022/11/24 15:27:11 [info] 28#28 "netbox" application started
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    restart: unless-stopped
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
  netbox-worker:
    restart: unless-stopped
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    restart: unless-stopped
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  postgres:
    restart: unless-stopped
    ports:
      - 5432:5432
  tls:
    restart: unless-stopped
    image: slothcroissant/caddy-cloudflaredns:latest
    env_file: env/caddy.env
    depends_on:
      - netbox
    volumes:
      - ./cert.crt:/etc/ssl/private/cert.crt:ro,z
      - ./key.key:/etc/ssl/private/key.key:ro,z
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80   # Allows for http redirection
      - 443:443
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped
```
