### ISSUE TITLE
services.netbox-worker.depends_on contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by mik0s** [netbox-community/netbox-docker#900]
### Current Behavior

[root@netbox new-netbox]# docker-compose pull
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.netbox-housekeeping.depends_on contains an invalid type, it should be an array
services.netbox-worker.depends_on contains an invalid type, it should be an array

### Expected Behavior

Updated to current branch and now I'm getting this error.

### Docker Compose Version

docker-compose version 1.24.1, build 4667896b docker-py version: 3.7.3 CPython version: 3.6.8 OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.13
  GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

39f64e64790ace9dc29637c2a01a7ce80d67ed4b

### The git Status

```text
# On branch drw
# Your branch is ahead of 'origin/release' by 30 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   env/netbox.env
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       docker-compose.override.yml_
#       netbox.sql
no changes added to commit (use "git add" and/or "git commit -a")
```

### Startup Command

docker-compose pull

### NetBox Logs

```text
nothing, I do docker-compose pull only
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 8080
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - /etc/pki/netbox.crt:/etc/ssl/private/cert.crt:ro,z
      - /etc/pki/netbox.key:/etc/ssl/private/key.key:ro,z
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80 # Allows for http redirection
      - 443:443
```
