### ISSUE TITLE
ValueError: Found wrong number (0) of constraints for dcim_device(virtual_chassis_id, vc_position)

### ISSUE THREAD

**Issue by TnTBass** [netbox-community/netbox-docker#920]
### Current Behavior

I attempted to upgrade from Netbox 3.3.9 to 3.4.0, but I received an error in during the database migration step.

### Expected Behavior

I would expect the upgrade to proceed as normal.

### Docker Compose Version

Docker Compose version v2.14.1

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    docker-compose.override.yml.example
        modified:   docker-compose.yml
        modified:   env/netbox.env
        modified:   env/postgres.env

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        letsencrypt/
        traefik.yaml
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
netbox  | ⚙️ Applying database migrations
netbox  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox  | 🧬 loaded config '/etc/netbox/config/myconfig.py'
netbox  | Operations to perform:
netbox  |   Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization, wireless
netbox  | Running migrations:
netbox  |   Applying circuits.0039_unique_constraints... OK
netbox  |   Applying circuits.0040_provider_remove_deprecated_fields... OK
netbox  |   Applying circuits.0041_standardize_description_comments... OK
netbox  |   Applying tenancy.0008_unique_constraints... OK
netbox  |   Applying tenancy.0009_standardize_description_comments... OK
netbox  |   Applying ipam.0061_fhrpgroup_name... OK
netbox  |   Applying ipam.0062_unique_constraints... OK
netbox  |   Applying ipam.0063_standardize_description_comments... OK
netbox  |   Applying extras.0078_unique_constraints... OK
netbox  |   Applying extras.0079_scheduled_jobs... OK
netbox  |   Applying extras.0080_customlink_content_types... OK
netbox  |   Applying extras.0081_exporttemplate_content_types... OK
netbox  |   Applying extras.0082_savedfilter... OK
netbox  | Traceback (most recent call last):
netbox  |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox  |     execute_from_command_line(sys.argv)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox  |     utility.execute()
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
netbox  |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
netbox  |     self.execute(*args, **cmd_options)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
netbox  |     output = self.handle(*args, **options)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
netbox  |     res = handle_func(*args, **kwargs)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle
netbox  |     post_migrate_state = executor.migrate(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
netbox  |     state = self._migrate_all_forwards(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
netbox  |     state = self.apply_migration(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
netbox  |     state = migration.apply(state, schema_editor)
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 130, in apply
netbox  |     operation.database_forwards(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/operations/models.py", line 564, in database_forwards
netbox  |     alter_together(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 533, in alter_unique_together
netbox  |     self._delete_composed_index(
netbox  |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 589, in _delete_composed_index
netbox  |     raise ValueError(
netbox  | ValueError: Found wrong number (0) of constraints for dcim_device(virtual_chassis_id, vc_position)
```

### Content of docker-compose.override.yml

```yaml
services:
  netbox:
    restart: unless-stopped
    container_name: netbox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox.rule=Host(`netbox-test.example.com`)"
      - "traefik.http.routers.netbox.entrypoints=websecure"
      - "traefik.http.routers.netbox.tls=true"
      - "traefik.http.routers.netbox.tls.certresolver=myresolver"
      - "traefik.http.routers.netbox.tls.domains[0].main=*.example.com"
      - "traefik.http.routers.netbox.tls.domains[0].sans=example.com"
    ports:
      - "8080"

  netbox-worker:
    restart: unless-stopped

  netbox-housekeeping:
    restart: unless-stopped

  redis:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

  redis-cache:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

  traefik:
    restart: unless-stopped
    image: traefik:v2.9
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik-test.example.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=lan"
      - "traefik.http.middlewares.lan.ipwhitelist.sourcerange=10.0.0.0/24"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.metrics.service=prometheus@internal"
    environment:
      - CLOUDFLARE_EMAIL=me@example.com
      - CLOUDFLARE_DNS_API_TOKEN=supersecrettoken
    ports:
       - 80:80
       - 443:443
       - 8082
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - "./letsencrypt:/letsencrypt"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami-test.example.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  redis-worker-exporter:
    image: oliver006/redis_exporter
    depends_on:
    - redis
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_PASSWORD: ...

  redis-cache-exporter:
    image: oliver006/redis_exporter
    depends_on:
    - redis-cache
    environment:
      REDIS_ADDR: redis://redis-cache:6379
      REDIS_PASSWORD: ...

  prometheus:
    image: prom/prometheus
    depends_on:
    - redis-cache-exporter
    - redis-worker-exporter
    - netbox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus-test.example.com`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
    ports:
      - '9090:9090'
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus/data

  # grafana
  grafana:
    image: grafana/grafana
    depends_on:
    - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_SECRET_KEY: ...
      GF_METRICS_ENABLED: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana-test.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    ports:
      - '3000:3000'
    volumes:
    #- ./monitoring/grafana/plugins/:/var/lib/grafana/plugins/:z,ro
    #- ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/:z,ro
    #- ./monitoring/grafana/dashboards/:/etc/grafana/dashboards/:z,ro
    - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
```
