### ISSUE TITLE
Docker Hub: Tag latest and v3.4-2.4.0 is not v3.4.3-2.4.0

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-docker#927]
### Current Behavior

on dockerhub latest and v3.4-2.4.0 is v3.4.2-2.4.0 

### Expected Behavior

latest and v3.4-2.4.0 should be v3.4.3-2.4.0

### Docker Compose Version

 v2.15.1

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:45:08 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:42:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

39c7de4af41703108f8b3af7274bc65813c41799

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.
```

### Startup Command

docker compose up -d

### NetBox Logs

```text
no
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    restart: always
    depends_on:
      - netbox
    command:
      #- --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --accesslog=true
    ports:
    # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik-config/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
        - ./traefik-certs:/tools/certs

  netbox:
    restart: always
   # ports:
   #   - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbox-http.rule=Host(`host...`)"
      - "traefik.http.routers.netbox-http.entrypoints=web"
      - "traefik.http.routers.netbox-http.middlewares=netbox-https"
      - "traefik.http.middlewares.netbox-https.redirectscheme.scheme=https"
      - "traefik.http.routers.netbox-https.rule=Host(`host...local`)"
      - "traefik.http.routers.netbox-https.entrypoints=websecure"
      - "traefik.http.routers.netbox-https.tls=true"
      - "traefik.http.services.netbox.loadbalancer.server.port=8080"

  netbox-worker:
    restart: always
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    labels:
      - "traefik.enable=false"

  netbox-housekeeping:
    restart: always
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    labels:
      - "traefik.enable=false"

  postgres:
    restart: always
    labels:
      - "traefik.enable=false"

  redis:
    restart: always
    labels:
      - "traefik.enable=false"

  redis-cache:
    restart: always
    labels:
      - "traefik.enable=false"
```
